### ISSUE TITLE
实例化第二个CnOcr的时候报错

### ISSUE THREAD

**Issue by xxxss** [breezedeus/cnocr#100]
如果只实例化第一个CnOcr的时候正常。
但是再要实例化一个
In [5]: standard_ocr = CnOcr()
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-5-1d08456dd4de> in <module>
----> 1 standard_ocr = CnOcr()

D:\Anaconda3\lib\site-packages\cnocr\cn_ocr.py in __init__(self, model_name, model_epoch, cand_alphabet, root, context)
    152         self._hp._loss_type = None  # infer mode
    153
--> 154         self._mod = self._get_module(context)
    155
    156     def _assert_and_prepare_model_files(self):

D:\Anaconda3\lib\site-packages\cnocr\cn_ocr.py in _get_module(self, context)
    187             data_shapes,
    188             network=network,
--> 189             context=context,
    190         )
    191         return mod

D:\Anaconda3\lib\site-packages\cnocr\cn_ocr.py in load_module(prefix, epoch, data_names, data_shapes, network, context)
    107     )
    108     mod.bind(for_training=False, data_shapes=data_shapes)
--> 109     mod.set_params(arg_params, aux_params, allow_missing=False)
    110     return mod
    111

D:\Anaconda3\lib\site-packages\mxnet\module\module.py in set_params(self, arg_params, aux_params, allow_missing, force_init, allow_extra)
    348             self.init_params(initializer=None, arg_params=arg_params, aux_params=aux_params,
    349                              allow_missing=allow_missing, force_init=force_init,
--> 350                              allow_extra=allow_extra)
    351             return
    352

D:\Anaconda3\lib\site-packages\mxnet\module\module.py in init_params(self, initializer, arg_params, aux_params, allow_missing, force_init, allow_extra)
    307         for name, arr in sorted(self._arg_params.items()):
    308             desc = InitDesc(name, attrs.get(name, None))
--> 309             _impl(desc, arr, arg_params)
    310
    311         for name, arr in sorted(self._aux_params.items()):

D:\Anaconda3\lib\site-packages\mxnet\module\module.py in _impl(name, arr, cache)
    298                 else:
    299                     if not allow_missing:
--> 300                         raise RuntimeError("%s is not presented" % name)
    301                     if initializer is not None:
    302                         initializer(name, arr)

RuntimeError: crnn2_seq-fc_bias is not presented

**Comment by yerui2018** [comment]
这个问题，我也遇到到了，不过看不懂，也不知道怎么解决。只能看作者了。

**Comment by breezedeus** [comment]
为啥要实例化2个。。

**Comment by myuanz** [comment]
> 为啥要实例化2个。。

先大范围分块检测识别, 有时人们先验地知道有些块是确定范围的字符组合, 因此对于大范围得到的某些块再做特化识别

**Comment by xxxss** [comment]
比如先初始化一个默认的ocr识别文字。然后到另一行全是数字的图片，为了提高识别率，初始化一个识别数字的ocr

**Comment by breezedeus** [comment]
> 比如先初始化一个默认的ocr识别文字。然后到另一行全是数字的图片，为了提高识别率，初始化一个识别数字的ocr

明白了😅 可能比较简单的方法是改下代码，可以在调用时把范围传进去。这个问题我之后也会看看

**Comment by xxxss** [comment]
不只是范围吧，主要是识别数字的那个参数得在实例化的时候传。比如我处理title的时候可能希望尽量是识别文字，到了时间戳那一行希望尽量识别数字和标点。到了详情又希望尽量是汉字。而全部一起识别效果很差，所以我才切成一片一片的处理

**Comment by breezedeus** [comment]
> 不只是范围吧，主要是识别数字的那个参数得在实例化的时候传。比如我处理title的时候可能希望尽量是识别文字，到了时间戳那一行希望尽量识别数字和标点。到了详情又希望尽量是汉字。而全部一起识别效果很差，所以我才切成一片一片的处理

所以我说要改下代码啊。另外，能不能提供几个识别错的图片，我也说说看

**Comment by yerui2018** [comment]
> 不只是范围吧，主要是识别数字的那个参数得在实例化的时候传。比如我处理title的时候可能希望尽量是识别文字，到了时间戳那一行希望尽量识别数字和标点。到了详情又希望尽量是汉字。而全部一起识别效果很差，所以我才切成一片一片的处理

为了限定字符，每次去实列化类，有点奇怪的。我是改造了一下CnOcr类，在预测时，传递限定字符值进去。
def ocr_for_single_lines(self, img_list,cand_alphabet):

修改了这个函数。要灵活用嘛，哈哈。

**Comment by breezedeus** [comment]
https://github.com/breezedeus/cnocr/pull/103 已修复，发布新版 v1.2.2。基于上面讨论的使用场景，可以有以下两种方法：

1. 通过类函数 `CnOcr.set_cand_alphabet(cand_alphabet)` 设置不同的 `cand_alphabet`。
2. 实例化多个值，如

```
cnocr1=CnOcr(name='instance1')
cnocr2=CnOcr(name='instance2')
```

【注：不同的实例需要指定不同的值。】
