### ISSUE TITLE
terminate called after throwing an instance of 'dmlc::Error'

### ISSUE THREAD

**Issue by zhangqizky** [breezedeus/cnocr#101]
what() [12:05:44]src/operator/nn/pooling.cc:193 Check falied:param.kernel[1]<=dshape_nchw[3]+2*param.pdd[1]:kernel size(2) exceeds input(1 padded to 1)
stack trace:
[bt] path/libmxnet.so(+0x307d3b)

请问这个是因为mxnet版本不匹配嘛？并不是每个case都出现，出现原因不明。。。

**Comment by breezedeus** [comment]
@zhangqizky 麻烦传两张会出错的图片上来，我复现看看

**Comment by GeorgeXiaojie** [comment]
我也遇到同样的问题，批量处理的时候，处理一批文件之后会出现dmlc::Error，单独把报dmlc::Error错误的文件拿出来处理，可以正常处理。

**Comment by zhangqizky** [comment]
您的邮件已收到，我会尽快回复，谢谢。张琦
