### ISSUE TITLE
构想：建立一个开源的中文OCR数据集

### ISSUE THREAD

**Issue by RuikangSun** [breezedeus/cnocr#104]
像是语音识别有基于CC0的 https://voice.mozilla.org/ ，而图像识别领域暂时没有如此的开源数据集。
我们是不是也可以建立一个开放共享的OCR库呢？通过志愿者的贡献来扩充数据集，提高各种模型的识别准确度。

**Comment by arckalsun** [comment]
目前我的场景都是屏幕文字识别，如果有的话，希望能分区分场景和字体。

**Comment by RuikangSun** [comment]
Close old issues.
