### ISSUE TITLE
复杂图表无法识别

### ISSUE THREAD

**Issue by wangguanhua** [breezedeus/cnocr#106]
如题，cnocr识别结果为[['2', '.', '*', '.', '*', '^', 'e', '2', '*', 'e', '.', '.', '.', ' ', 'l'], ['8', '|'], ['。', '打', '印', '人', ':', '凌', '云', '打', '印', '时', '间', ':', '2', '0', '1', '3', '-', '1', '2', '-', '2', '6', '1', '8', ':', '5', '8', ':', '4', '8']]。我用ctpn+crnn虽然正确率不高，但基本都识别的出来。
![4](https://user-images.githubusercontent.com/25172472/83484407-6f45f100-a4d7-11ea-8a20-7e7b1f366288.png)

**Comment by breezedeus** [comment]
没法直接识别这么复杂的图片，可以结合 https://github.com/breezedeus/cnstd 使用

**Comment by wangguanhua** [comment]
您好，cnstd我配合使用了一下，给我的感觉是对文字检测还不够准确，小的文本行有很多没检测出来，而且cnocr针对小文字貌似识别效果不佳

**Comment by breezedeus** [comment]
的确检测识别的不好，你可以调调参数试试，但估计也不会好太多。像这种表格需要利用专门处理表格的工具了。

**Comment by yilu1015** [comment]
推荐两款从PDF提取表格信息的libraries: [Tabula](https://github.com/tabulapdf/tabula)或[camelot](https://github.com/atlanhq/camelot)。可以考虑jpg=>pdf=>ocr=>提取。实在不行，百度有图表识别的API。

**Comment by yerui2018** [comment]
这种表格，我们采用abbyy的引擎，再通过cnocr去识别。毫无压力。因为abbyy的引擎识别率不太高。所以结合cnocr，可以用于生产环境的。

**Comment by wangguanhua** [comment]
> 这种表格，我们采用abbyy的引擎，再通过cnocr去识别。毫无压力。因为abbyy的引擎识别率不太高。所以结合cnocr，可以用于生产环境的。

您好，请问您说的这个有什么教程吗？

**Comment by yerui2018** [comment]
> > 这种表格，我们采用abbyy的引擎，再通过cnocr去识别。毫无压力。因为abbyy的引擎识别率不太高。所以结合cnocr，可以用于生产环境的。
> 
> 您好，请问您说的这个有什么教程吗？

没有什么教程哦，abbyy是商业软件服务，不是技术人员一个人搞定的。

**Comment by wangguanhua** [comment]
> > > 这种表格，我们采用abbyy的引擎，再通过cnocr去识别。毫无压力。因为abbyy的引擎识别率不太高。所以结合cnocr，可以用于生产环境的。
> > 
> > 
> > 您好，请问您说的这个有什么教程吗？
> 
> 没有什么教程哦，abbyy是商业软件服务，不是技术人员一个人搞定的。

我还以为单纯的是abbyy软件呢。。。abbyy的软件我也有用，的确识别效果不行

**Comment by yerui2018** [comment]
> > > > 这种表格，我们采用abbyy的引擎，再通过cnocr去识别。毫无压力。因为abbyy的引擎识别率不太高。所以结合cnocr，可以用于生产环境的。
> > > 
> > > 
> > > 您好，请问您说的这个有什么教程吗？
> > 
> > 
> > 没有什么教程哦，abbyy是商业软件服务，不是技术人员一个人搞定的。
> 
> 我还以为单纯的是abbyy软件呢。。。abbyy的软件我也有用，的确识别效果不行

我们可以交流交流，wechat:657189156

**Comment by wangguanhua** [comment]
> 推荐两款从PDF提取表格信息的libraries: [Tabula](https://github.com/tabulapdf/tabula)或[camelot](https://github.com/atlanhq/camelot)。可以考虑jpg=>pdf=>ocr=>提取。实在不行，百度有图表识别的API。

百度的这个我有试过，还可以。但有一些场合是不能联网的，所以只能再看看其他的。至于您说的Camelot这两个我先看看，谢谢您了。

**Comment by yilu1015** [comment]
> > 推荐两款从PDF提取表格信息的libraries: [Tabula](https://github.com/tabulapdf/tabula)或[camelot](https://github.com/atlanhq/camelot)。可以考虑jpg=>pdf=>ocr=>提取。实在不行，百度有图表识别的API。
> 
> 百度的这个我有试过，还可以。但有一些场合是不能联网的，所以只能再看看其他的。至于您说的Camelot这两个我先看看，谢谢您了。

不用谢，我也在找寻开源的解决提取表格图片方法，如果您有思路的话，烦请指教。
