### ISSUE TITLE
识别的速度慢

### ISSUE THREAD

**Issue by oohurbert** [breezedeus/cnocr#11]
这个项目安装、使用简单，但是在识别的时候速度比较慢。一开始是调用了多行检测的函数，确实是慢，后来改成单行检测，速度有提升，但是比原版的crnn-mxnet还是慢不少。而且没有支持批量识别，在实际使用时会比较慢。

**Comment by breezedeus** [comment]
终于有人真的在用了 :( 现在的实现方式有天然的效率问题。之后会考虑重写代码重新训练模型，解决效率问题

**Comment by gogogo365** [comment]
升级硬件能提升速度么，比如加装P106-100这样的卡，或者更新的CPU。

另外感觉单行识别质量比多行识别质量要差很多。同一个图片，多行识别正确，单行识别出错。

**Comment by breezedeus** [comment]
@oohurbert v1.0.0发布了，预测效率更高，欢迎使用~

**Comment by breezedeus** [comment]
> 另外感觉单行识别质量比多行识别质量要差很多

这个很怪，按理不应该的，能提供下图片文件么？
