### ISSUE TITLE
模型是否能输出识别的字符的概率？

### ISSUE THREAD

**Issue by universewill** [breezedeus/cnocr#110]
模型是否能输出识别的字符的概率？怎么取到识别字符结果的概率值？

**Comment by zonghaofan** [comment]
_gen_line_pred_chars重写如下即可。

    def _del_repeat(self, a):
        # a = [1, 0, 0, 2, 2, 2]
        opt = [1] * len(a)
        for i in range(len(a)):
            if a[i] == 0:
                opt[i] = 0
            if i >= 1:
                if a[i] == a[i - 1]:
                    opt[i] = 0
        return np.nonzero(np.array(opt))




    def _gen_line_pred_chars(self, line_prob, img_width, max_img_width):
        """
        Get the predicted characters.
        :param line_prob: with shape of [seq_length, num_classes]
        :param img_width:
        :param max_img_width:
        :return:
        """
        class_ids = np.argmax(line_prob, axis=-1)
        indexs = self._del_repeat(class_ids)
        probs = np.max(line_prob, axis=-1)
        fin_probs = probs[indexs]
        # print('==fin_probs:', fin_probs)
        # print('==len(fin_probs):', len(fin_probs))
        if img_width < max_img_width:
            comp_ratio = self._hp.seq_len_cmpr_ratio
            end_idx = img_width // comp_ratio
            if end_idx < len(class_ids):
                class_ids[end_idx:] = 0
        prediction, start_end_idx = CtcMetrics.ctc_label(class_ids.tolist())
        # print('==prediction:', prediction)
        alphabet = self._alphabet
        res = [alphabet[p] if alphabet[p] != '<space>' else ' ' for p in prediction]
        return (res, fin_probs)
