### ISSUE TITLE
安装要求不兼容某些CUDA版本

### ISSUE THREAD

**Issue by gdzqzzx** [breezedeus/cnocr#116]
发现在colab的CUDA10.1下无法直接使用pip直接安装。
经测试后，发现要先分别安装gluoncv和对应CUDA版本下的mxnet，再去除依赖直接安装cnocr：
`!pip install gluoncv`
`!pip install mxnet-cu101`
`!pip install cnocr --no-dependencies`
更多cuda版本对应的mxnet可参见[mxnet-cu101 1.6.0](https://pypi.org/project/mxnet-cu101/)。
建议后续更新requirement.txt。

**Comment by breezedeus** [comment]
对，GPU要用GPU版本，我之后改下，谢谢
