### ISSUE TITLE
推理速度很慢

### ISSUE THREAD

**Issue by wanglaiqi** [breezedeus/cnocr#117]
检测加识别两个模块推理一张图片要20s. 基于一块GPU

**Comment by breezedeus** [comment]
慢在检测。这个速度应该是没用上GPU。用GPU要安装 mxnet gpu版本

**Comment by wanglaiqi** [comment]
已经解决速度的问题，在cn_std.py脚本中的 修改如下：
![image](https://user-images.githubusercontent.com/9366714/86000173-bfb15f80-ba3f-11ea-80d1-dbfadee1ee48.png)
当前推理一张图片在100ms左右

**Comment by breezedeus** [comment]
咦，初始化不是有个参数 `context`，传入 `gpu` 不管用？

**Comment by breezedeus** [comment]
应该是我之前代码有问题，https://github.com/breezedeus/cnstd/issues/3

把原来的 `net.load_parameters(ckpt_path)` 改成 `net.load_parameters(ckpt_path, ctx=ctx)` 应该就行。

**Comment by helloxuejuxi** [comment]
现在的最新版都没有cnstd函数里都没这个了啊，我这也发现gpu文本检测居然比cpu检测慢一倍，只改了个context=gpu

**Comment by breezedeus** [comment]
新版的速度应该不慢了吧。 DEMO： https://share.streamlit.io/breezedeus/cnstd/st-deploy/cnstd/app.py 这里可以看效果
