### ISSUE TITLE
ocr_for_single_lines为什么会比ocr_for_single_line还慢？

### ISSUE THREAD

**Issue by dennisgu** [breezedeus/cnocr#121]
@breezedeus 作者你好。
我尝试输入30行不同长短的单行文字图片进行识别，分别用ocr_for_single_line和ocr_for_single_lines测试识别，发现相差有2～3倍。
为何ocr_for_single_lines的batch机制比用循环调用ocr_for_single_line要慢？
是我输入的图片数据类型或尺寸有什么要求吗？

**Comment by breezedeus** [comment]
是不是图片长度差距很大

**Comment by dennisgu** [comment]
> 是不是图片长度差距很大

对，有点字少就很短，有点一行一整句话

**Comment by breezedeus** [comment]
用batch会把图片都padding到最大长度，所以长度差异很大可能会慢。

**Comment by dennisgu** [comment]
> 用batch会把图片都padding到最大长度，所以长度差异很大可能会慢。

而且发现短图片的文字内容也容易识别错误
