### ISSUE TITLE
模型里面为什么包含loss function,能去掉吗?没用过MXnet

### ISSUE THREAD

**Issue by Ted-Yee** [breezedeus/cnocr#122]
有幸发现大老这么好的项目,正准备移植到嵌入式端部署,不过模型文件包含了loss function部分,导致模型转换不过,能有什么方法加载预训练的模型,然后去掉loss function部分节点重新保存?我没用过MXnet,网上没找到相关资料,请大佬指教

**Comment by breezedeus** [comment]
嗯，导入部分参数是不是就行了
