### ISSUE TITLE
crnnX_seq-fc_bias is not presented

### ISSUE THREAD

**Issue by wikithink** [breezedeus/cnocr#123]
环境：
win10 x64
python 3.7.4
cnocr 1.2.2
MXnet 1.6.0
已经下载安装了densenet-lite-fc  densenet-lite-gru 两个模型
电脑没有GPU

`
from cnocr import CnOcr
ocr=CnOcr()
res=ocr.ocr("D:/win/06.png")
`
报错误：crnnX_seq-fc_bias is not presented 【其中X可能是1,2,3,4,5,6等数字】
如何处理？谢谢！

**Comment by breezedeus** [comment]
你初始化了多个实例吧。初始化时加入name参数，具体看文档有介绍
