### ISSUE TITLE
你好 这个bug 是版本问题吗

### ISSUE THREAD

**Issue by liugj101** [breezedeus/cnocr#129]
UserWarning: Cannot decide type for the following arguments. Consider providing them as input:
	data: None
  input_sym_arg_type = in_param.infer_type()[0]
![image](https://user-images.githubusercontent.com/43821055/97070458-e442d000-160a-11eb-9ebd-ef2368e8e5d9.png)

**Comment by liugj101** [comment]
求解答

**Comment by liugj101** [comment]
mxnet版本问题，

**Comment by breezedeus** [comment]
warning 而已，忽略就好
