### ISSUE TITLE
是否考虑按类型识别呢

### ISSUE THREAD

**Issue by Jinnrry** [breezedeus/cnocr#13]
中文识别非常完美，但是还有一点小问题，0和o,1和l，9和g，这种经常识别错，是否可以加一个文本类型的参数呢？

**Comment by breezedeus** [comment]
什么叫文本类型的参数？识别是数字还是字母？

**Comment by jiangwei1995910** [comment]
对，某些场景下，我只需要识别数字或者中文或者英文

**Comment by breezedeus** [comment]
@jiangwei1995910 这个需求挺好的，改动一下现有代码就行，下个版本支持吧~

**Comment by breezedeus** [comment]
@Jinnrry V1.1.0 已支持 `按类型识别` ~

**Comment by Jinnrry** [comment]
太赞了！ 感谢作者的付出
