### ISSUE TITLE
Gpu memory isnt fully freed up. 

### ISSUE THREAD

**Issue by djaym7** [breezedeus/cnocr#137]
Doing simple allocation and clearing cache and deleting variable doesn't clear all memory!

'''
ctx = mx.gpu(0)
arr = mx.nd.ones((200,200), ctx=ctx)
del arr
ctx.empty_cache()
'''
Memory always remains in gpu, after several runs of loading model, del model and empty_cache(), stale memory in gpu keeps increasing until CUDA throws out of memory error.

**Comment by zhreshold** [comment]
Note that only reserve memory pool can be cleaned by `empty_cache`, CUDA runtime will reserve up to few hundred MBs which can not be released.

**Comment by djaym7** [comment]
Got it, will try to put that in separate process using multiprocessing which should clear up the memory. Thanks
