### ISSUE TITLE
cn_ocr ocr中的参数是什么   为什么出现Inappropriate argument type

### ISSUE THREAD

**Issue by zhangchunyang1995** [breezedeus/cnocr#14]
cnocr\cn_ocr.py", line 144, in ocr
    raise TypeError('Inappropriate argument type.')
TypeError: Inappropriate argument type.

**Comment by jiangwei1995910** [comment]
文件路径，还有numpy，好像传文件也支持

**Comment by zhangchunyang1995** [comment]
谢谢

**Comment by breezedeus** [comment]
嗯，是的
