### ISSUE TITLE
给大家展示一下本项目的辣鸡效果

### ISSUE THREAD

**Issue by SakigamiYang** [breezedeus/cnocr#148]
![4](https://user-images.githubusercontent.com/15279135/118577211-89e2aa00-b7bc-11eb-93af-74fe6340f126.png)
<img width="683" alt="5" src="https://user-images.githubusercontent.com/15279135/118577215-8cdd9a80-b7bc-11eb-8007-9ac401bb0554.png">

**Comment by breezedeus** [comment]
好好看文档说的使用场景

**Comment by wolfog** [comment]
> ![4](https://user-images.githubusercontent.com/15279135/118577211-89e2aa00-b7bc-11eb-93af-74fe6340f126.png) <img alt="5" width="683" src="https://user-images.githubusercontent.com/15279135/118577215-8cdd9a80-b7bc-11eb-8007-9ac401bb0554.png">
垃圾，你可以提供改进，没必要这样说话。

**Comment by breezedeus** [comment]
<img width="1258" alt="image" src="https://user-images.githubusercontent.com/6712673/183036798-fd40b01d-b532-46f7-9325-9e89a2aa4eaa.png">

https://huggingface.co/spaces/breezedeus/cnocr
