### ISSUE TITLE
识别速度慢，精度也不太好

### ISSUE THREAD

**Issue by hoodlum1980** [breezedeus/cnocr#149]
这是两个最主要的问题。就是速度比较慢，然后配合 cnocr 识别出来的精度太低，难以达到实用的程度，这我还不知道什么原因。
此外就是技术细节描述不够详细，比如 cropped_img 字段是 top-down 还是 bottom-up 的顺序？

**Comment by luolinll1212** [comment]
遇到同样的问题，cnstd+cnocr，window没有任何问题，把代码移动到linux，识别结果完全对不上，亟待解决。
