### ISSUE TITLE
下周准备更新下实现方式，提升速度。先立个flag~

### ISSUE THREAD

**Issue by breezedeus** [breezedeus/cnocr#15]

**Comment by gogogo365** [comment]
升级硬件能提升速度么，比如加装P106-100这样的卡，或者更新的CPU。
另外感觉单行识别质量比多行识别质量要差很多。同一个图片，多行识别正确，单行识别出错。

**Comment by kevinchen1223** [comment]
期待~~

**Comment by breezedeus** [comment]
flag得往后延一两个月了，最近自己和机器的资源都很紧张。

**Comment by breezedeus** [comment]
@gogogo365 方便的话可以提供下badcases么？我过段时间一起看看

**Comment by Suley** [comment]
期待

**Comment by breezedeus** [comment]
Finally！

v1.0.0发布了，预测效率更高，欢迎使用~

**Comment by kevinchen1223** [comment]
赞！！太棒啦

BreezeDeus <notifications@github.com> 于2019年7月25日周四 上午11:23写道：
