### ISSUE TITLE
生僻字支持不太好

### ISSUE THREAD

**Issue by impvd** [breezedeus/cnocr#157]
用输入法第一个字母 `a` 的截图测试
<img width="300" alt="sogou_a" src="https://user-images.githubusercontent.com/37371804/138270846-feb1c664-477a-43a8-8ed2-dc14dc8b492c.png">

识别:
```python
(['a', '啊', '阿', '吖', '钢'], 0.11811017990112305), 
(['腌', '嘎', '珂', '酶'], 0.15254665911197662), 
(['呵', 'O', '爱', '哎'], 0.13976244628429413), 
(['唉', ':', '-', '(', '安', '昂'], 0.09503354132175446)
```

如下失败：
<img width="292" alt="image" src="https://user-images.githubusercontent.com/37371804/138271103-4ab55011-7eb1-414b-8756-ef0381115982.png">

**Comment by breezedeus** [comment]
没办法，生僻字就会有这个问题，训练数据中可能很少出现
