### ISSUE TITLE
较大的空白区域会影响densenet-s-gru的推断

### ISSUE THREAD

**Issue by laozhanghahaha** [breezedeus/cnocr#158]
较大的空白区域会影响densenet-s-gru的推断

![image](https://user-images.githubusercontent.com/12216214/139026775-f96b5824-fe66-4771-8d21-93a02ebf1721.png)

gru预测结果
 \>准按照_《〈驻场yf管'玉理暂行办>法&执行
fc预测结果
 准按照《驻场管理暂行办法执行》。

**Comment by breezedeus** [comment]
嗯，的确存在这个问题，正在想办法解决。现在的话你可以先用cnstd做文本检测，可以去掉空白
