### ISSUE TITLE
import 报错Cannot find the MXNet library

### ISSUE THREAD

**Issue by summmer121** [breezedeus/cnocr#170]
RuntimeError: Cannot find the MXNet library.
List of candidates:
F:\python\project\pythonProject\v\lib\site-packages\mxnet\libmxnet.dll
F:\python\project\pythonProject\v\lib\site-packages\mxnet\../../lib/libmxnet.dll
F:\python\project\pythonProject\v\lib\site-packages\mxnet\../../build/libmxnet.dll
F:\python\project\pythonProject\v\lib\site-packages\mxnet\../../build\libmxnet.dll
F:\python\project\pythonProject\v\lib\site-packages\mxnet\../../build\Release\libmxnet.dll
F:\python\project\pythonProject\v\lib\site-packages\mxnet\../../windows\Release\libmxnet.dll

**Comment by breezedeus** [comment]
如果使用旧版本，MXNet在Windows下要单独看看怎么装，可以搜下应该很多资料。
