### ISSUE TITLE
这个模型有可能移植到移动端吗？

### ISSUE THREAD

**Issue by Jinnrry** [breezedeus/cnocr#18]
如果我把这个模型移植到移动端有可能吗？手机的性能能跑动这个模型吗？

**Comment by breezedeus** [comment]
估计有点困难。移动端我记得阿里有相关的开源项目，可以考虑用那个。

**Comment by yuanqin27** [comment]
阿里相关移动端开源项目可以分享下吗？

**Comment by Jinnrry** [comment]
https://github.com/Jinnrry/captcha_check 我用这个项目改了下，移植到移动端没问题

**Comment by yuanqin27** [comment]
移植的方法有参考的文档推荐吗？最近在部署移动端，各种错误，快坚持不下去了。

**Comment by Jinnrry** [comment]
TensorFlow部署移动端文章应该很多吧，一共就没几个方法，官方文档连中文都有了。各种博客也满地都是。
https://www.tensorflow.org/lite/guide/android?hl=zh_cn

但是前提是数据预处理你得和训练的时候一致

**Comment by hflserdaniel** [comment]
@Jinnrry 您好，请问下模型移植到手机端整体性能如何？是需要首先用tf改写模型然后再部署到移动端吗？冒昧请教，十分感谢！

**Comment by Jinnrry** [comment]
@hflserdaniel  不是，我是使用的另外的模型，这个模型我以前尝试移植过，遇到的问题太多了，就放弃了
