### ISSUE TITLE
cnocr识别数字比较差

### ISSUE THREAD

**Issue by hp742740676** [breezedeus/cnocr#19]
cnocr识别数字比较差，能提高数字识别准确度吗

**Comment by breezedeus** [comment]
能提供示例文件吗？试试v1.0.0？

**Comment by zhliji2** [comment]
0容易失败为O

**Comment by breezedeus** [comment]
0 O, 1 l 这种的确很容易误判

**Comment by breezedeus** [comment]
@hp742740676 @zhliji2 可以试试 V1.1.0

**Comment by wilderchen** [comment]
+1, 图片数字识别度相对要低...我提供几个...

![20200422193902](https://user-images.githubusercontent.com/28138033/80235094-cf04dd00-868b-11ea-9105-8db84c4697fa.png)
![20200422211313](https://user-images.githubusercontent.com/28138033/80235141-e348da00-868b-11ea-9eeb-572ca1ca8952.png)

**Comment by breezedeus** [comment]
试了下，的确效果不好。下一版会改进数字识别的精度~

**Comment by xxllp** [comment]
ocr 看来识别准还是有点难

**Comment by yerui2018** [comment]
作者提供的模型我们使用起来已经感觉很棒了。想一招吃天下，肯定是不容易的，我们可以结合自己的应用需求特点，加上ctpn，加上限定字符集。效果还是很不错的 @breezedeus 加油！

**Comment by xxllp** [comment]
限定字符集 这个是咋做的 @yerui2018

**Comment by yerui2018** [comment]
作者最新版的代码已经默认支持该功能了的。

**Comment by breezedeus** [comment]
感谢 @yerui2018 。v1.2的模型已经优化了对数字的识别，这两天就会发布了

**Comment by breezedeus** [comment]
新版基本解决这个问题了，可以试试
