### ISSUE TITLE
the format of data_root, train_file and test_file 

### ISSUE THREAD

**Issue by ShaneYS** [breezedeus/cnocr#2]
thanks for your great work.
I want to train net on my own data, but I don't know the format of training set. So can you tell me the format of image name and train txt file?
Besides, is there any requirement for image size?
Thanks

**Comment by breezedeus** [comment]
Hi.
You can find the data format desc here: https://github.com/diaomin/crnn-mxnet-chinese-text-recognition. Like this:

## Data Preparation
1. Download the Synthetic Chinese Dataset(contributed by https://github.com/senlinuc/caffe_ocr and many thanks)

  A glance of the dataset:

  * almost 3.6 million synthetic chinese text images.
  * 5,990 different categories in total.
  * each image has a length of 10 characters.
2. Create train.txt and text.txt with the format like this:

```
           image_name1 label1_1 label1_2 label1_3...
           image_name2 label2_1 label2_2 label2_3...
```

**Comment by breezedeus** [comment]
Examples:

![image](https://user-images.githubusercontent.com/6712673/55635509-77cb6a80-57f3-11e9-97ce-e4be1352dbc5.png)

**Comment by breezedeus** [comment]
Image size should be 280 (width) * 32 (height). An example:
https://github.com/breezedeus/cnocr/blob/master/examples/20457890_2399557098.jpg
