### ISSUE TITLE
运行 cnocr train -m densenet_lite_136-fc --index-dir data/test --train-config-fp docs/examples/train_config.json 训练自己数据集出错

### ISSUE THREAD

**Issue by ViviKing414** [breezedeus/CnOCR#202]
LightningDataModule.__init__() got an unexpected keyword argument 'train_transforms'

**Comment by ViviKing414** [comment]
python ./tests/test_trainer.py 也是出错 

TypeError: __init__() got an unexpected keyword argument 'train_transforms'

**Comment by breezedeus** [comment]
参考这里： https://github.com/breezedeus/CnOCR/issues/195
