### ISSUE TITLE
  WARNING: cnocr 2.1.0 does not provide the extra 'serve'

### ISSUE THREAD

**Issue by JaneConan** [breezedeus/CnOCR#210]
Error: No such command "serve".

cnocr -h
Usage: cnocr [OPTIONS] COMMAND [ARGS]...

Options:
  -h, --help  Show this message and exit.

Commands:
  evaluate
  predict
  resave    训练好的模型会存储训练状态，使用此命令去掉预测时无关的数据，降低模型大小
  train

root@0016:~# pip install cnocr[serve]
Requirement already satisfied: cnocr[serve] in /usr/local/lib/python3.8/dist-packages (2.1.0)
  WARNING: cnocr 2.1.0 does not provide the extra 'serve'

**Comment by breezedeus** [comment]
你的pip没找到最新版的cnocr，你先更新下pip，然后再装cnocr试试

**Comment by JaneConan** [comment]
root@4-0016:~# python3 -m pip install --upgrade pip
Requirement already satisfied: pip in /usr/local/lib/python3.8/dist-packages (22.2.2)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
root@4-0016:~# python3 -m pip install --upgrade pip
Requirement already satisfied: pip in /usr/local/lib/python3.8/dist-packages (22.2.2)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
root@4-0016:~# python3 -m pip install cnocr[serve]
Requirement already satisfied: cnocr[serve] in /usr/local/lib/python3.8/dist-packages (2.1.0)
WARNING: cnocr 2.1.0 does not provide the extra 'serve'

**Comment by JaneConan** [comment]
应该已经时最新版的pip了吧，22.2.2

**Comment by breezedeus** [comment]
pip源的问题？应该安装 2.2.2 版本。

```bash
$ pip install cnocr==
Looking in indexes: https://pypi.doubanio.com/simple
ERROR: Could not find a version that satisfies the requirement cnocr== (from versions: 0.1.1, 0.2.0, 1.0.0, 1.1.0, 1.1.1, 1.1.2.1, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.3.1, 2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.1.1.1, 2.1.2, 2.1.2.1, 2.2, 2.2.1, 2.2.2)
ERROR: No matching distribution found for cnocr==
```

**Comment by JaneConan** [comment]
![image](https://user-images.githubusercontent.com/26090153/193187427-fa82d662-00fe-4001-86bb-e6c81ee923aa.png)

![image](https://user-images.githubusercontent.com/26090153/193187534-c146c0fb-4b67-4cf4-ba7d-cee203b29965.png)

可以了，我再试试👍
