### ISSUE TITLE
How to det and rec using CnOcr.ocr

### ISSUE THREAD

**Issue by toffeecat** [breezedeus/CnOCR#219]
'batch_size' is one of the parameters in CnOcr.ocr(),
but the function only takes one image as input.
What should I do if the number of images to be OCR is large?
how can I input a batch of images?
![1670732593467](https://user-images.githubusercontent.com/94946328/206886308-5299c181-7e32-4cd2-bd16-795c587fd3dc.png)

**Comment by breezedeus** [comment]
CnOcr.ocr() can only process one image at a time. One image may contain multiple lines of text. The parameter of `rec_batch_size` (for the latest version) means how many lines of text will be processed at the same time.

**Comment by Toffeecat** [comment]
I still have question about  the meaning of parameter "batch_size", will it help reduce process time cost when a lot of CnOcr.ocr() is called?

**Comment by breezedeus** [comment]
If you run on a GPU, it will be faster with 'batch_size'. On CPUs it maybe not.
