### ISSUE TITLE
Over resource limits on Streamlit Cloud

### ISSUE THREAD

**Issue by HHuangShao** [breezedeus/CnOCR#229]
Hey there :wave: Just wanted to let you know that [your app on Streamlit Cloud deployed from this repo](https://breezedeus-cnocr-cnocrapp-st-deploy-qz3rht.streamlit.app/breezedeus/cnocr/st-deploy/cnocr/app.py) has gone over its resource limits. Access to the app is temporarily limited. Visit the app to see more details and possible solutions.

**Comment by breezedeus** [comment]
Thank you very much. It has been dead for a long time😅. Try this: 
https://huggingface.co/spaces/breezedeus/cnocr
