### ISSUE TITLE
示例代码，调用出错

### ISSUE THREAD

**Issue by cqsir** [breezedeus/CnOCR#235]
代码：
---------------

> 
```
from cnocr import CnOcr
img_fp ='c:\\a.png'
ocr = CnOcr()  # 所有参数都使用默认值
out = ocr.ocr(img_fp)
print(out)
```

错误提示：
--------------
Traceback (most recent call last):
  File "t.py", line 13, in <module>
    ocr = CnOcr()
  File "C:\Users\cqsir\.virtualenvs\w2-RAi9_op1\lib\site-packages\cnocr\cn_ocr.py", line 169, in __init__
    self.det_model = CnStd(
  File "C:\Users\cqsir\.virtualenvs\w2-RAi9_op1\lib\site-packages\cnstd\cn_std.py", line 98, in __init__
    self.det_model = det_cls(
  **File "C:\Users\cqsir\.virtualenvs\w2-RAi9_op1\lib\site-packages\cnstd\ppocr\pp_detector.py", line 108, in __init__
    if img_h is not None and img_w is not None and img_h > 0 and img_w > 0:
  TypeError: '>' not supported between instances of 'str' and 'int'**

补充：
----------------
使用ocr = CnOcr(det_model_name='naive_det')，是可以调用成功的。

只要调用到cn_std.py就会出现上面的错误，原因是啥？

python版本3.8.0

**Comment by cqsir** [comment]
上面的img_fp ='c:\a.png'，实际上是‘c:\\a.png’的，自动发布后github自动去掉一个\

**Comment by breezedeus** [comment]
cnstd是最新版吗？试试把cnstd自动下载的模型删掉，让它重新下载一下，有可能是模型文件不完整导致的。

**Comment by cqsir** [comment]
感谢！可以了。

之前因为自动安装模型失败，按错误提示折腾半天，手动下载放到目标目录，导致出错。

无法自动安装安装模型的原因是，开了梯子。把梯子关了就正常了。
