### ISSUE TITLE
python3.11下安装遇到torchvision版本的问题

### ISSUE THREAD

**Issue by wangjnethca** [breezedeus/CnOCR#239]
requirements.txt中以来torchvision==0.11.1，但pip3安装时提示没有对应版本，默认的安装0.15.1在调用时存在问题。

请问后续有相应的升级计划吗？

**Comment by breezedeus** [comment]
torchvision <= 0.14.1 应该都是可以的，setup.py中并没有做约束。 0.15.1 还没测过。
