### ISSUE TITLE
英语单词之间空格识别不了

### ISSUE THREAD

**Issue by zhang0557kui** [breezedeus/cnocr#24]
英语单词之间空格识别不了

**Comment by breezedeus** [comment]
嗯，目前还无法识别空格

**Comment by breezedeus** [comment]
@zhang0557kui 新版已经可以识别空格了

**Comment by yht4work** [comment]
你好，

想问下能支持对于中文空格的识别么？比如表格中的情况
![1413121037-0](https://user-images.githubusercontent.com/92348729/150270852-3412fbe4-1ab3-4c5b-9d90-d173b3d126ea.jpg)
