### ISSUE TITLE
模型启动的cpu占用率

### ISSUE THREAD

**Issue by with-him777** [breezedeus/CnOCR#245]
目前模型启动会倾向于占用全部的cpu核心，你知道为什么吗,比如我有100个核，cnOCR会尝试开100个进程跑模型，但实际速度和2个核跑差不多,而当我有100个核的时候，想限制程序只用2个核，cnOCR还是会开100个进程，导致竞争卡死

**Comment by helloHKTK** [comment]
遇到同样的问题了，请问如何解决？

**Comment by breezedeus** [comment]
backend 如果使用的 `pytorch`，后面用的就是pytorch，否则就是onnx。参看以下ChatGPT给出的答案，可以试试，不确定真的有效。需要更好的控制，也可以考虑跑docker容器。

<img width="820" alt="image" src="https://github.com/breezedeus/CnOCR/assets/6712673/32529074-d914-4777-b8c8-834ed644326d">
<img width="751" alt="image" src="https://github.com/breezedeus/CnOCR/assets/6712673/40a0dd2f-63aa-4b31-821f-07a19da1716b">
