### ISSUE TITLE
广告图片识别效果还有待提高，加油~

### ISSUE THREAD

**Issue by cleghom** [breezedeus/cnocr#25]
多谢，但是也发现，对于电商网页广告中包含无序文字的图片，识别效果不太好

**Comment by breezedeus** [comment]
@cleghom 多谢使用。是的，目前cnocr主要还是面向标准的书面体。

**Comment by swordspoet** [comment]
> @cleghom 多谢使用。是的，目前cnocr主要还是面向标准的书面体。

标准的印刷体，使用pytesseract就能达到很不错的效果，非标准的字体识别才是最关键的。
