### ISSUE TITLE
有无支持python3.11计划？

### ISSUE THREAD

**Issue by tan9p** [breezedeus/CnOCR#258]
RT，当前在装CnOCR时，会提示只支持python 3.7到3.10的版本

**Comment by breezedeus** [comment]
没有，主要是依赖的包不支持3.11

**Comment by d9394** [comment]
Python 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] on linux
正常

**Comment by 5m1le71ger** [comment]
Python 3.11.7能安装成功，但是在这之前我用最新的3.12版本安装，会出现这样的错误。于是我退回3.11就成功了

AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
