### ISSUE TITLE
Raise up an

### ISSUE THREAD

**Issue by YuanyangZhang** [breezedeus/CnOCR#259]
[WARNING 2023-06-27 15:21:53,723 _assert_and_prepare_model_files:167] no onnx file is found in C:\Users\张远洋\AppData\Roaming\cnocr\2.2\densenet_lite_136-fc 

requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

Process finished with exit code 1

**Comment by breezedeus** [comment]
需要梯子。。模型自动下载使用的是HuggingFace的服务，但HuggingFace国内已被墙。具体参考：https://www.breezedeus.com/cnocr
