### ISSUE TITLE
cannot import name 'CnOcr'

### ISSUE THREAD

**Issue by xuweidongkobe** [breezedeus/cnocr#26]
按照要求，用pip安装了cnocr，pip list看了下也有cnocr库，但是跑脚本的时候，报如下错误，想问一下，该怎么解决。
from cnocr import CnOcr
ImportError: cannot import name 'CnOcr'

**Comment by breezedeus** [comment]
你用的是哪个版本？这种错误一般是你装包的python环境跟你运行python的环境不同

**Comment by xuweidongkobe** [comment]
@breezedeus 我是centos7系统，然后装了conda，建了个python环境，然后在这个环境里装的cnocr，运行脚本就遇到这个错误。但是，我退出这个环境，直接在centos7里跑这个脚本，就不报错。然后就很疑惑，明明是在虚拟环境里装的cnocr，为什么虚拟环境里不能用，外面的环境却能用？

**Comment by breezedeus** [comment]
所以可能是你装错了地方么？可以装个其他包试试是否有同样的问题

**Comment by swordspoet** [comment]
> @breezedeus 我是centos7系统，然后装了conda，建了个python环境，然后在这个环境里装的cnocr，运行脚本就遇到这个错误。但是，我退出这个环境，直接在centos7里跑这个脚本，就不报错。然后就很疑惑，明明是在虚拟环境里装的cnocr，为什么虚拟环境里不能用，外面的环境却能用？

我也遇到了同样的问题，在PyCharm执行会报错`ImportError: cannot import name 'CnOcr'`，我猜测应该是那个来自DropBox的模型文件下载在home目录下面，所以无论你的项目还是从命令行执行都要到home目录下去。
![image](https://user-images.githubusercontent.com/14816130/63745787-a991ba80-c8d5-11e9-9e60-a4c7d1f925b3.png)

**Comment by swordspoet** [comment]
> 按照要求，用pip安装了cnocr，pip list看了下也有cnocr库，但是跑脚本的时候，报如下错误，想问一下，该怎么解决。
> from cnocr import CnOcr
> ImportError: cannot import name 'CnOcr'

跑脚本的错误目前还不知道是怎么回事。

**Comment by crashiers** [comment]
同样问题，已解决

**Comment by breezedeus** [comment]
@crashiers 欢迎帮忙提pr。按理import的时候不会导入模型，不应该由模型文件导致错误。

**Comment by Chandler-Lu** [comment]
别把py的文件名命名为cnocr.py，不然 import 会自动尝试从文件导入。。

**Comment by redjack001** [comment]
@crashiers 请问最后怎样解决，因为我有同样问题，然而我在用Anaconda以及Windows.
