### ISSUE TITLE
pip install CnOCR忽略本地已安装torch

### ISSUE THREAD

**Issue by DannyP0** [breezedeus/CnOCR#266]
本地环境
* Ubuntu 18.04, 
* Python 3.8.10
* PyTorch 1.13.1 (通过pip install torch==1.13.1安装)

执行安装命令 pip install cnocr==2.2.2，会自动安装torch最新版2.0.1，
安装log提示Collecting torch>=1.8.0 (from cnocr==2.2.2)，意味着 torch>=1.8.0即可？
我想用我本地已安装的torch，而非最新版torch。

**Comment by breezedeus** [comment]
可以先安装下cnocr依赖的包（本项目里的requirements.txt，把其中的torch, torchvision注释掉）：
```bash
pip install -r requirements.txt
```

然后安装cnocr但不安装它的依赖：
```bash
pip install cnocr --no-deps
```
