### ISSUE TITLE
请问训练的数据集就是 Synthetic Chinese Dataset吗？

### ISSUE THREAD

**Issue by jaycecd** [breezedeus/cnocr#28]

**Comment by breezedeus** [comment]
主要是这个，还有一些自己生成的

**Comment by zhang0557kui** [comment]
请问一下，自己生成的训练数据不是定长的吧，我看Synthetic Chinese Dataset里的数据都是定长的，是不是训练支持不定长的数据啊

**Comment by breezedeus** [comment]
自己生成的数据也是定长的啊，因为这个可以自己控制。现在应该是不支持变长图片训练的

**Comment by jaycecd** [comment]
> 自己生成的数据也是定长的啊，因为这个可以自己控制。现在应该是不支持变长图片训练的

请问这个定长是指图片的尺寸是固定的吗？例如280*32？

**Comment by breezedeus** [comment]
> > 自己生成的数据也是定长的啊，因为这个可以自己控制。现在应该是不支持变长图片训练的
> 
> 请问这个定长是指图片的尺寸是固定的吗？例如280*32？

是的。
