### ISSUE TITLE
百度云里面的模型

### ISSUE THREAD

**Issue by GnJoeln** [breezedeus/CnOCR#289]
请问我第一次运行cnocr没有自动下载zip文件，我去百度云下下来了，之后放在了C:\Users\ASUS\AppData\Roaming\cnocr下，但是好像没什么作用，似乎只对1.0的版本有用，它会自定解压zip文件，在C:\Users\ASUS\AppData\Roaming\cnocr\models文件夹下生成好像是1.0的模型。需要怎么解压百度云下的各种文件呢

**Comment by breezedeus** [comment]
`pip show cnocr` 查看安装的版本。然后下载对应版本的模型。比如 cnocr==2.2.4.1，那就下载 2.2/* 的模型。
按理现在会自动下载模型。可以考虑删了已下载的模型自动重下
