### ISSUE TITLE
请问自己训练的话，数据集如何生成

### ISSUE THREAD

**Issue by lizheng2112** [breezedeus/cnocr#29]
为什么train.txt和test.txt文件名后跟的是一串数字，这些数字和文字之间的对照关系是如何建立的？

**Comment by breezedeus** [comment]
数字是图片里每个字的id，id对应关系在 [label_cn.txt](https://github.com/breezedeus/cnocr/blob/master/examples/label_cn.txt) 文件里定义的。第一行对应的字，id就是`1`；第二行对应的字，id就是`2`；……

**Comment by lizheng2112** [comment]
多谢..!
