### ISSUE TITLE
2.3.0.1版本使用自定义的字符集合似乎不起作用

### ISSUE THREAD

**Issue by liewstar** [breezedeus/CnOCR#306]
2.2版本是没有问题的，但是升级到2.3版本之后，使用自定义字符集合之后，识别任何图片都是空字符

**Comment by liewstar** [comment]
升级2.3版本的同时，我的python环境也从3.7升到了3.10

**Comment by breezedeus** [comment]
有具体示例吗？可以把代码是图片都发一下

**Comment by liewstar** [comment]
只把cncocr的版本切换到2.2的最后一个版本的话，能够正常输出。切换到2.3.0.1就是如下。
```python
from cnocr import CnOcr

ocr = CnOcr(rec_vocab_fp='label_cn.txt')
out = ocr.ocr('test.png')
print(out)

```
![图片](https://github.com/breezedeus/CnOCR/assets/93535922/51409e17-e948-4a90-8ef8-7485590b5699)
![图片](https://github.com/breezedeus/CnOCR/assets/93535922/d756a1ba-76a8-48c5-a0dd-83c232e4601d)
![图片](https://github.com/breezedeus/CnOCR/assets/93535922/2cd95c9c-bb91-40c1-849b-bd3d0449217f)



> 有具体示例吗？可以把代码是图片都发一下

**Comment by breezedeus** [comment]
<img width="293" alt="image" src="https://github.com/breezedeus/CnOCR/assets/6712673/63e779b2-e439-4c05-a362-2e8584ee7ac3">
你这用法有问题，V2.3 的 label_cn.txt 跟之前不一样了。如果你是跟默认文件一样，就不用传这个参数。如果你是自己训练的模型，那就得把模型名称和模型文件路径都传进来。

**Comment by liewstar** [comment]
> <img alt="image" width="293" src="https://private-user-images.githubusercontent.com/6712673/293587469-63e779b2-e439-4c05-a362-2e8584ee7ac3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxMTY0MTksIm5iZiI6MTcwNDExNjExOSwicGF0aCI6Ii82NzEyNjczLzI5MzU4NzQ2OS02M2U3NzliMi1lNDM5LTRjMDUtYTM2Mi0yZTg1ODRlZTdhYzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDFUMTMzNTE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODNiZjY4OGQwMTVmMTcyZjNlNDMwOTkxZmFlMWZiMGM3NmQ5M2RhNjk0NzAyMzVhMzg5NWY0NDU2MjQ5ZGQwYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.xePFw8w_CAeNC_mmIMyaI7ZURoqrn0SirmvvhdY3PWY"> 你这用法有问题，V2.3 的 label_cn.txt 跟之前不一样了。如果你是跟默认文件一样，就不用传这个参数。如果你是自己训练的模型，那就得把模型名称和模型文件路径都传进来。

原来是这样吗，但是我目前需要把py程序打包成exe的话，2.2的时候我是把txt放在cnocr这个文件夹下面，然后一起打包，没有传rec_vocab_fp这个参数，程序会自己在cnocr里面找到这个txt，运行是没问题的。同样的方法，2.3就不行，即便是一样的不传参数也不行。       如果我打包的成exe时候，文件夹没有这个txt的话，会提示cnocr下面缺少这个txt。  

目前2.3的话大概就是打包成exe的话，这个字符集合要从哪里拿。

**Comment by kai2128** [comment]
有试过使用 2.3 的字符集吗?
[label_cn.txt](https://github.com/breezedeus/CnOCR/blob/8c8930e0da36ed663f348789eb30b84872cf5b68/cnocr/label_cn.txt)
