### ISSUE TITLE
Synthetic Chinese Dataset数据集中图像中都是10个字，自己生成的数据集也要保证每个图像10个字吗

### ISSUE THREAD

**Issue by zhang0557kui** [breezedeus/cnocr#31]

**Comment by breezedeus** [comment]
不确定行不行。如果可以就尽量都用10个字的，如果不行就试试不是10个字的吧。。

**Comment by lizheng2112** [comment]
如果自己有大量数据，训练新的模型可以不用十个字；如果加载作者已经完成的模型继续训练，自己生成的数据集小于10个字的话效果不好（比如是3个字，训练出的模型会把三个字长度的区域预测成一个字好像）。

**Comment by yerui2018** [comment]
> 如果自己有大量数据，训练新的模型可以不用十个字；如果加载作者已经完成的模型继续训练，自己生成的数据集小于10个字的话效果不好（比如是3个字，训练出的模型会把三个字长度的区域预测成一个字好像）。

你那有使用继续训练得出是这个结论吗？

**Comment by daixiangzi** [comment]
> 不确定行不行。如果可以就尽量都用10个字的，如果不行就试试不是10个字的吧。。

你好，我想问下，我看你这里面的训练代码都是固定尺寸的词条。但是在评估代码里面，是先按照h等比例缩放到32。这样评估岂不是和训练代码中训练时候的尺寸不一致？，比如我训练时用的32*280，那么我个人认为评估阶段也应该缩放32*280，而不是32*new_w.
