### ISSUE TITLE
同一高度下的多个有序文本块，会因为较大的高度差导致输出错误的排列顺序

### ISSUE THREAD

**Issue by skci** [breezedeus/CnOCR#316]
**描述：**
项目没有直接提供对行高敏感性调整的选项，识别时经常会遇到，有序的几个文本块在同一高度下，个别文本块略高而被率先输出，导致原本有序的文本变的混乱。

**示例：**
![image](https://github.com/breezedeus/CnOCR/assets/31680619/76c8f571-a094-42d2-9665-d18e4611e4a2)
期望输出：['X0', 'X0', 'X0', 'X204', 'X59']
实际输出：['X204', 'X0', 'X0', 'X0', 'X59']

**Comment by breezedeus** [comment]
结果中给出了每段文字的位置，自己按照需要排个序就好了。

**Comment by skci** [comment]
对，我目前就是这样解决的，但如果项目自身带有一个可调节的敏感度参数就更好了😘
