### ISSUE TITLE
微调效果很差

### ISSUE THREAD

**Issue by pujianjian** [breezedeus/CnOCR#317]
你好，我想微调训练让模型对μ的识别更好，发现微调之后模型乱识别，效果巨差，不知道是什么原因？
我微调的图片只有μm，然后图片比较小，标签就是
****.jpg μ m
如果可以帮忙解答将感激不尽

**Comment by breezedeus** [comment]
多少图片

**Comment by pujianjian** [comment]
因为μ这个识别效果不好，我这边想优化一下这个，数据集这样制作应该是正确的吧
![微信图片_20240307174811](https://github.com/breezedeus/CnOCR/assets/48307115/0ccc20d1-f0c4-4e9d-86e9-910212ccb346)

**Comment by breezedeus** [comment]
格式是没问题的。不过你这不会就是一张图吧

**Comment by pujianjian** [comment]
有三百多张这样的图，图也基本长一样，因为我们检测都是这样的
