### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 19: invalid start byte

### ISSUE THREAD

**Issue by jisiallen** [breezedeus/CnOCR#325]
<img width="929" alt="image" src="https://github.com/breezedeus/CnOCR/assets/9688374/7cbc4669-4b4a-4f9e-bcca-eb7895f3e333">

系统  win 10
应该怎么解决

**Comment by breezedeus** [comment]
改过 vocab_fp 对应的文件？
