### ISSUE TITLE
为什么截图和拍照之后的识别率相差巨大

### ISSUE THREAD

**Issue by masiqi** [breezedeus/cnocr#33]
发现截图的识别率接近100%，但是同样的截图拍照之后再识别基本上就识别不出来了，我需要做哪些处理才可以让拍照之后的识别率能够显著提升，谢谢！
![](https://beeguess.oss-cn-hangzhou.aliyuncs.com/t2.png)
![](https://beeguess.oss-cn-hangzhou.aliyuncs.com/t3.png)
上面的可以识别，下面的就识别不了

**Comment by masiqi** [comment]
似乎做过锐化之后就可以比较好的识别了

**Comment by breezedeus** [comment]
赞。再不行做个二值化试试，用opencv
