### ISSUE TITLE
Error “Illegal instruction (core dumped)” 

### ISSUE THREAD

**Issue by qpwl12345** [breezedeus/cnocr#34]
My CPU doesn't support AVX. Is there any ways to install lower version or install cnocr from source???

**Comment by qpwl12345** [comment]
tried version 0.2.0, but same problem

**Comment by breezedeus** [comment]
I think the problem is caused by Mxnet. Maybe you can try installing from source, but no guaranteed.

**Comment by fujiajun** [comment]
CPU指令集支持AVX，在centos上执行脚本也出现了 Illegal instruction~~~

**Comment by xiaoyuergo** [comment]
> CPU指令集支持AVX，在centos上执行脚本也出现了

请问你后来怎么解决的？我也出现这问题了

**Comment by JinghaoZ** [comment]
same problem
[root@localhost ~]# cat /proc/cpuinfo
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 45
model name	: Intel(R) Xeon(R) CPU E5-2407 0 @ 2.20GHz
stepping	: 7
microcode	: 0x718
cpu MHz		: 2021.008
cache size	: 10240 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm epb ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm arat pln pts spec_ctrl intel_stibp flush_l1d
bogomips	: 4389.56
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

**Comment by yudun1989** [comment]
坐等解决方式，我是在虚拟机(PVE)里面的ubuntu安装的。也报同样错误
