### ISSUE TITLE
请问支持变长图片识别是怎么做到的？切图吗？

### ISSUE THREAD

**Issue by zzks** [breezedeus/cnocr#35]
多谢作者的分享！
训练图片应该是定长吧？
请问变长图片识别是怎么做到的？切成训练图片长度再塞入batch做inference吗？
我用定长图片训练，感觉图片长度越长，越难训练而且效果越差。
请问你是如何做到长图片也能OCR效果这么好？

**Comment by breezedeus** [comment]
> 多谢作者的分享！
> 训练图片应该是定长吧？
> 请问变长图片识别是怎么做到的？切成训练图片长度再塞入batch做inference吗？
> 我用定长图片训练，感觉图片长度越长，越难训练而且效果越差。
> 请问你是如何做到长图片也能OCR效果这么好？

可以参考 https://github.com/breezedeus/cnocr/blob/master/cnocr/cn_ocr.py#L176，大概意思就是先pad到相同长度，然后再对预测结果用mask做长度约束，mask逻辑在函数[_gen_line_pred_chars()](https://github.com/breezedeus/cnocr/blob/master/cnocr/cn_ocr.py#L176)里面。

**Comment by zzks** [comment]
多谢指点！
看了源码，它对需要OCR的长图片做了切割，切成小图做识别，然后def _gen_line_pred_chars 这块把小图结果做整合输出的部分没有看懂。对mxnet不熟悉，只能下载下来实际跑一下观察看看了。
