### ISSUE TITLE
https://www.dropbox.com 网站国内停用了

### ISSUE THREAD

**Issue by patientmingming** [breezedeus/cnocr#37]
https://www.dropbox.com 网站国内停用了，导致几个包无法下载

**Comment by patientmingming** [comment]
Downloading C:\Users\ming\AppData\Roaming\cnocr\cnocr-models-v1.0.0.zip from https://www.dropbox.com/s/7w8l3mk4pvkt34w/cnocr-models-v1.0.0.zip?dl=1...
download failed due to ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))), retrying, 4 attempts left
Downloading C:\Users\ming\AppData\Roaming\cnocr\cnocr-models-v1.0.0.zip from https://www.dropbox.com/s/7w8l3mk4pvkt34w/cnocr-models-v1.0.0.zip?dl=1...
download failed due to ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))), retrying, 3 attempts left
Downloading C:\Users\ming\AppData\Roaming\cnocr\cnocr-models-v1.0.0.zip from https://www.dropbox.com/s/7w8l3mk4pvkt34w/cnocr-models-v1.0.0.zip?dl=1...
download failed due to ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))), retrying, 2 attempts left
Downloading C:\Users\ming\AppData\Roaming\cnocr\cnocr-models-v1.0.0.zip from https://www.dropbox.com/s/7w8l3mk4pvkt34w/cnocr-models-v1.0.0.zip?dl=1...
download failed due to ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))), retrying, 1 attempt left

**Comment by breezedeus** [comment]
嗯，可以使用提供的百度云直接下载到本地就行了
