### ISSUE TITLE
为什么win7执行代码后会阻塞不能结束,win10可以

### ISSUE THREAD

**Issue by studyaa** [breezedeus/cnocr#42]
测试了三台win7,两台win10
在win7上代码运行完都不能够结束 一直阻塞

**Comment by breezedeus** [comment]
啊。。python版本相同吗？

**Comment by studyaa** [comment]
win10是3.5和3.6, win7是两个3.5一个3.7
很奇怪

**Comment by breezedeus** [comment]
我在Windows 7上简单试过 3.6，倒是没发现这个问题

**Comment by studyaa** [comment]
不行呀3.6也不行 只要一导入cnocr或者mxnet这些包就会阻塞
会是什么原因啊大佬T.T

**Comment by breezedeus** [comment]
> 不行呀3.6也不行 只要一导入cnocr或者mxnet这些包就会阻塞
> 会是什么原因啊大佬T.T

我测过真没问题。。 你能debug下具体卡在哪步么？

**Comment by ResistanceTo** [comment]
我遇到了相同的问题，windows7 x32   python 3.6.8。测试程序结束后无法停止，处于假死状态，ctrl+z/c都无法退出。在程序最后一段加exit()都无法停止。

**Comment by Haibeike01** [comment]
> > 不行呀3.6也不行 只要一导入cnocr或者mxnet这些包就会阻塞
> > 会是什么原因啊大佬T.T
> 
> 我测过真没问题。。 你能debug下具体卡在哪步么？

我也是遇到这个问题，win7，python3.6，也是识别完成后就卡住程序无法结束，Ctrl+z也不行，exit（）也不行

**Comment by breezedeus** [comment]
只导入mxnet也会阻塞么？

**Comment by breezedeus** [comment]
如果导入mxnet有问题的话，可以尝试换个mxnet版本看看

**Comment by songbaoming** [comment]
确实是 mxnet 的问题：https://github.com/apache/incubator-mxnet/issues/11163

**Comment by gmx1992** [comment]
Proposed solution
https://blog.csdn.net/CR_Alvin/article/details/110631788
