### ISSUE TITLE
A4扫描稿识别率太低

### ISSUE THREAD

**Issue by 81519434** [breezedeus/cnocr#51]
我发现识别用截图工具截图一小段文字没有问题，如果喂给一个完整的4A扫描件，几乎无法识别。
图片附着如下：
![img016](https://user-images.githubusercontent.com/9690089/71393576-2e080600-2648-11ea-949e-2de35ce345d2.jpg)
![img013](https://user-images.githubusercontent.com/9690089/71393578-2e080600-2648-11ea-8f34-a392061330c3.jpg)
![img014](https://user-images.githubusercontent.com/9690089/71393580-2ea09c80-2648-11ea-8c97-29205c3cfa56.jpg)
![img015](https://user-images.githubusercontent.com/9690089/71393581-2ea09c80-2648-11ea-8657-0b1179d8ce52.jpg)

**Comment by 81519434** [comment]
目前的解决方案是：结合另外一个项目[darknet-ocr](https://github.com/chineseocr/darknet-ocr)，识别文字范围，然后将所有文字区域图片切割下来，再喂给cnocr。这样识别率挺高。

**Comment by breezedeus** [comment]
@81519434 应该是切行那块导致问题。导致切行出现问题的原因很可能是扫描稿边上的黑边导致的，可以考虑把黑边切掉后再由cnocr识别。切黑边的简单方法就是四边裁掉一些。

**Comment by 81519434** [comment]
已经尝试过你说的方法，但是对于一些文件还是不行。
![Uploading image.png…]()

大标题，和正文 之间的间隙太大。还是会导致识别率很低

**Comment by breezedeus** [comment]
嗯，是的。切行结果很影响最后的识别。如果时间扛得住，先做文本检测挺好的👍
