### ISSUE TITLE
百度云盘的模型是旧模型

### ISSUE THREAD

**Issue by jiaorui** [breezedeus/cnocr#52]
百度云盘的模型写着0.1.0版本，程序默认执行的是1.0.0，程序会报错

**Comment by breezedeus** [comment]
@jiaorui 你是从master分支获取的链接么？我看了是1.0的模型啊。。

**Comment by jiaorui** [comment]
您好，现在看到的是新模型，之前下载的模型是0.1.0，解压之后的文件也没有版本号，感谢回答
