### ISSUE TITLE
dropbox无法下载模型

### ISSUE THREAD

**Issue by xingyuezhiji** [breezedeus/cnocr#53]
你好，运行程序的时候默认从dropbox下载模型，但是国内无法下载呀，请问怎么处理啊

**Comment by breezedeus** [comment]
可以使用提供的百度云直接下载到本地就行了。README里写了的。

**Comment by xingyuezhiji** [comment]
> 可以使用提供的百度云直接下载到本地就行了。README里写了的。

看到了，不好意思，谢谢哈
