### ISSUE TITLE
如果加入CTPN就完美了

### ISSUE THREAD

**Issue by hefangcan** [breezedeus/cnocr#54]
因为对于自然场景的文字识别不好友好，希望能加入CTPN对文本定位

**Comment by breezedeus** [comment]
本来是不计划加这个的，好像很多人需要。。之后考虑加进去好了～

**Comment by yerui2018** [comment]
我把TF框架的CTPN加进去了。整合用起来还是可以的。

**Comment by yerui2018** [comment]
> 本来是不计划加这个的，好像很多人需要。。之后考虑加进去好了～

@breezedeus 是考虑加入CTPN还是PSENet呢？

**Comment by breezedeus** [comment]
@yerui2018 悄悄告诉你，psenet初版模型已经有了，只是太大太慢，还需要优化。会考虑开个新项目放。psenet还是有点慢，也会尝试更快的模型。

**Comment by yerui2018** [comment]
> @yerui2018 悄悄告诉你，psenet初版模型已经有了，只是太大太慢，还需要优化。会考虑开个新项目放。psenet还是有点慢，也会尝试更快的模型。

@breezedeus 其实机器学习算法细节我是看不懂的，仅仅是把基于tf的ctpn结合着用了，只用在扫描件的识别场景中，效果还可以。在windows的cpu环境下，效率也不高。
github上开源的ctpn，我只修改了两个应用中碰到的问题：
1、ctpn检测后，把原图图片resize小了，我给改成了输出原图比例的分行小图片；
2、检测后输出的小图，顺序错乱，没有按照从上至下，这里我重新调整的顺序；

因为我不太懂，只是抱着能用的态度去搞的。期待你的杰作，哈哈。

**Comment by breezedeus** [comment]
> > @yerui2018 悄悄告诉你，psenet初版模型已经有了，只是太大太慢，还需要优化。会考虑开个新项目放。psenet还是有点慢，也会尝试更快的模型。
> 
> @breezedeus 其实机器学习算法细节我是看不懂的，仅仅是把基于tf的ctpn结合着用了，只用在扫描件的识别场景中，效果还可以。在windows的cpu环境下，效率也不高。
> github上开源的ctpn，我只修改了两个应用中碰到的问题：
> 1、ctpn检测后，把原图图片resize小了，我给改成了输出原图比例的分行小图片；
> 2、检测后输出的小图，顺序错乱，没有按照从上至下，这里我重新调整的顺序；
> 
> 因为我不太懂，只是抱着能用的态度去搞的。期待你的杰作，哈哈。

厉害👍

**Comment by xxllp** [comment]
各种场景化的文字识别准确率也是不高的 这个还是需要加数据训练嘛

**Comment by breezedeus** [comment]
> 各种场景化的文字识别准确率也是不高的 这个还是需要加数据训练嘛

对，可以用场景化文字做微调。

**Comment by breezedeus** [comment]
可以尝试文字检测工具包： https://github.com/breezedeus/cnstd
