### ISSUE TITLE
非标准书面体无法识别吗？

### ISSUE THREAD

**Issue by ayaya118** [breezedeus/cnocr#55]
您好，请问下非标准书面体无法识别吗，如下图，运行后的结果是空的

![1](https://user-images.githubusercontent.com/4150721/72326123-841d1600-36e9-11ea-9394-067dea2c7a81.png)

**Comment by breezedeus** [comment]
是的，目前不支持场景文字识别

**Comment by xxllp** [comment]
未来考虑支持吗

**Comment by breezedeus** [comment]
新版已支持
