### ISSUE TITLE
如果不用pip安装直接下载工程文件该怎么调用啊

### ISSUE THREAD

**Issue by li-x-q** [breezedeus/cnocr#56]
您好！我是一个新手，请教一下如果不用pip安装，直接下载工程文件该怎么调用啊，非常感谢！

**Comment by breezedeus** [comment]
最简单的方式就是pip安装啊，要不然你就得下载源代码，放到自己的代码里去。这不是好的使用方法。cnocr也同样依赖别的包需要pip安装。
