### ISSUE TITLE
pip安装失败，好像是提示找不到mxnet的1.5.0 1.4.1 版本

### ISSUE THREAD

**Issue by a865186652** [breezedeus/cnocr#60]
我试了从原地址下载，也试了好几个镜像，基本都是这个问题，下面是报错
ERROR: Could not find a version that satisfies the requirement mxnet<1.5.0,>=1.4.1 (from cnocr) (from versions: 0.11.1b20170915, 0.11.1b20170922, 0.11.1b20170929, 0.11.1b20171006, 0.11.1b20171013, 0.12.0b20171020, 0.12.0b20171027, 0.12.0, 0.12.1b20171103, 0.12.1, 1.0.0, 1.0.0.post1, 1.0.0.post3, 1.0.0.post4, 1.0.1b20180114, 1.0.1b20180121, 1.0.1b20180128, 1.0.1b20180202, 1.1.0b20180209, 1.1.0b20180216, 1.1.0.post0, 1.2.0b20180223, 1.2.0b20180302, 1.2.0b20180309, 1.2.0b20180323, 1.2.0b20180330, 1.2.0b20180406, 1.2.0b20180413, 1.2.0b20180420, 1.2.0b20180427, 1.2.0b20180504, 1.2.0, 1.6.0)
ERROR: No matching distribution found for mxnet<1.5.0,>=1.4.1 (from cnocr)

**Comment by breezedeus** [comment]
嗯，我过几天更新下版本，着急的话可以从这里下载mxnet 1.4.1 先安装： https://pypi.org/project/mxnet/1.4.1/

**Comment by a865186652** [comment]
> 嗯，我过几天更新下版本，着急的话可以从这里下载mxnet 1.4.1先安装：[https](https://pypi.org/project/mxnet/1.4.1/) ://pypi.org/project/mxnet/1.4.1/[](https://pypi.org/project/mxnet/1.4.1/)

收到，感谢大佬的及时帮助

**Comment by breezedeus** [comment]
V1.1.0 版已经放宽了约束了，应该能找到了~
