### ISSUE TITLE
大神，问下我这边安装的对不对

### ISSUE THREAD

**Issue by jsycshanhongyu** [breezedeus/cnocr#64]
新手哈，环境弄了好久。最后装了cnocr，总感觉缺少点啥，贴出来给你看看：

安装地址不像文中说的，在 ~/.cnocr
我这边的地址最后在python3.5  下 找到，其他目录我用find命令找不到
root@cloud:/usr/local/lib/python3.5/dist-packages/cnocr# ls
cn_ocr.py  consts.py  data_utils  fit  hyperparams  __init__.py  line_split.py  __pycache__  symbols  utils.py  __version__.py

下面跑 pip install cnocr的log

root@cloud:/usr/local/lib/python3.5/dist-packages/cnocr# pip install cnocr
Requirement already satisfied: cnocr in /usr/local/lib/python3.5/dist-packages (1.0.0)
Requirement already satisfied: mxnet<1.5.0,>=1.4.1 in /usr/local/lib/python3.5/dist-packages (from cnocr) (1.4.1)
Requirement already satisfied: gluoncv<0.4.0,>=0.3.0 in /usr/local/lib/python3.5/dist-packages (from cnocr) (0.3.0)
Requirement already satisfied: pillow>=5.3.0 in /usr/local/lib/python3.5/dist-packages (from cnocr) (7.1.1)
Requirement already satisfied: numpy<1.15.0,>=1.14.0 in /usr/local/lib/python3.5/dist-packages (from cnocr) (1.14.6)
Requirement already satisfied: requests>=2.20.0 in /usr/local/lib/python3.5/dist-packages (from mxnet<1.5.0,>=1.4.1->cnocr) (2.23.0)
Requirement already satisfied: graphviz<0.9.0,>=0.8.1 in /usr/local/lib/python3.5/dist-packages (from mxnet<1.5.0,>=1.4.1->cnocr) (0.8.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.5/dist-packages (from gluoncv<0.4.0,>=0.3.0->cnocr) (4.45.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.5/dist-packages (from gluoncv<0.4.0,>=0.3.0->cnocr) (3.0.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.5/dist-packages (from gluoncv<0.4.0,>=0.3.0->cnocr) (1.4.1)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.5/dist-packages (from requests>=2.20.0->mxnet<1.5.0,>=1.4.1->cnocr) (1.25.8)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.5/dist-packages (from requests>=2.20.0->mxnet<1.5.0,>=1.4.1->cnocr) (2020.4.5.1)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.5/dist-packages (from requests>=2.20.0->mxnet<1.5.0,>=1.4.1->cnocr) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.5/dist-packages (from requests>=2.20.0->mxnet<1.5.0,>=1.4.1->cnocr) (2.9)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.5/dist-packages (from matplotlib->gluoncv<0.4.0,>=0.3.0->cnocr) (2.4.7)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.5/dist-packages (from matplotlib->gluoncv<0.4.0,>=0.3.0->cnocr) (0.10.0)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.5/dist-packages (from matplotlib->gluoncv<0.4.0,>=0.3.0->cnocr) (2.8.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.5/dist-packages (from matplotlib->gluoncv<0.4.0,>=0.3.0->cnocr) (1.1.0)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from cycler>=0.10->matplotlib->gluoncv<0.4.0,>=0.3.0->cnocr) (1.5.2)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from kiwisolver>=1.0.1->matplotlib->gluoncv<0.4.0,>=0.3.0->cnocr) (3.3)

里面我没有找到 scripts/cnocr_predict.py，也没找到这个~/.cnocr/models   
期待您的回复，谢谢

**Comment by breezedeus** [comment]
@jsycshanhongyu `pip install cnocr` 按照完成后不会有 `scripts/cnocr_predict.py` 这个文件。你可以直接从github上下载这个文件使用，或者用 `git clone https://github.com/breezedeus/cnocr` 克隆下整个库

**Comment by jsycshanhongyu** [comment]
**谢谢回答，追问一个：下面是结构，执行你的那个脚本不行，是为什么？  我感觉我应该快成功了**。
drwxr-xr-x 4 root root     4096 Apr 13 22:27 ./
drwx------ 9 root root     4096 Apr 13 22:12 ../
drwxr-xr-x 8 root root     4096 Apr 13 22:27 cnocr/
-rw-r--r-- 1 root root 33226580 Apr 13 21:29 cnocr-models-v1.0.0.zip
drwxr-xr-x 2 root root     4096 Jul 24  2019 models/
root@cloud:~/.cnocr# cd cnocr/
root@cloud:~/.cnocr/cnocr# ll
total 108
drwxr-xr-x 8 root root  4096 Apr 13 22:27 ./
drwxr-xr-x 4 root root  4096 Apr 13 22:27 ../
drwxr-xr-x 7 root root  4096 Apr 13 21:53 cnocr/
drwxr-xr-x 2 root root  4096 Apr 13 21:40 docs/
drwxr-xr-x 2 root root  4096 Apr 13 21:40 examples/
drwxr-xr-x 8 root root  4096 Apr 13 21:40 .git/
-rw-r--r-- 1 root root    66 Apr 13 21:40 .gitattributes
-rw-r--r-- 1 root root 41980 Apr 13 21:40 LICENSE
-rw-r--r-- 1 root root  8391 Apr 13 21:40 README_cn.md
-rw-r--r-- 1 root root  7485 Apr 13 21:40 README.md
-rw-r--r-- 1 root root    93 Apr 13 21:40 requirements.txt
drwxr-xr-x 2 root root  4096 Apr 13 21:40 scripts/
-rw-r--r-- 1 root root  1767 Apr 13 21:40 setup.py
drwxr-xr-x 2 root root  4096 Apr 13 21:40 tests/
root@cloud:~/.cnocr/cnocr# vim setup.py 
root@cloud:~/.cnocr/cnocr# python scripts/cnocr_predict.py --file examples/multi-line_cn1.png
Illegal instruction
root@cloud:~/.cnocr/cnocr# python scripts/cnocr_predict.py --file examples/multi-line_cn1.png 
Illegal instruction
root@cloud:~/.cnocr/cnocr# cd scripts/
root@cloud:~/.cnocr/cnocr/scripts# python cnocr_predict.py --file ../examples/multi-line_cn1.png 
Illegal instruction
root@cloud:~/.cnocr/cnocr/scripts#

**Comment by jsycshanhongyu** [comment]
大神，求帮看看上述问题，执行报Illegal instruction 这个错，在线等

**Comment by breezedeus** [comment]
麻烦贴下具体的报错信息

**Comment by xiaoyuergo** [comment]
不好意思，刚个账号发不了信息，我换个账号贴下信息：
root@cloud:~/cnocr# python scripts/cnocr_predict.py --file examples/multi-line_cn1.png
Illegal instruction
root@cloud:~/cnocr# python3.4  scripts/cnocr_predict.py --file examples/multi-line_cn1.png
Traceback (most recent call last):
  File "scripts/cnocr_predict.py", line 28, in <module>
    from cnocr import CnOcr
  File "/root/cnocr/cnocr/__init__.py", line 1, in <module>
    from .cn_ocr import CnOcr
  File "/root/cnocr/cnocr/cn_ocr.py", line 19, in <module>
    import mxnet as mx
ImportError: No module named 'mxnet'
root@cloud:~/cnocr# python3.5  scripts/cnocr_predict.py --file examples/multi-line_cn1.png
Illegal instruction


**我ubuntu上个python版本，执行完 只能看到这些错。没其他了，mxnet 其实我是安装过的。

**Comment by breezedeus** [comment]
这个提示说明你装包装窜了，mxnet没在你运行的python下装。你可以通过 `python3.5 -m pip freeze` 查看当前环境下已经装好的包。cnocr是可以在python3.5下运行的

**Comment by xiaoyuergo** [comment]
root@cloud:~/cnocr# python3.5 -m pip freeze
certifi==2020.4.5.1
chardet==3.0.4
cnocr==1.0.0
colorama==0.2.5
cycler==0.10.0
gluoncv==0.3.0
graphviz==0.8.4
html5lib==0.999
idna==2.9
kiwisolver==1.1.0
matplotlib==3.0.3
mxnet==1.4.1
numpy==1.14.6
Pillow==7.1.1
pycurl==7.19.3
pygobject==3.12.0
pyodbc==4.0.30
pyparsing==2.4.7
python-apt===0.9.3.5ubuntu3
python-dateutil==2.8.1
requests==2.23.0
scipy==1.4.1
six==1.5.2
torch==1.4.0+cpu
torchvision==0.5.0+cpu
tqdm==4.45.0
unattended-upgrades==0.1
urllib3==1.25.8


查了 有安装，运行
root@cloud:~/cnocr# python3.5  scripts/cnocr_predict.py --file examples/rand_cn1.png
Illegal instruction
报Illegal instruction 这个错，没有其他提示了

**Comment by breezedeus** [comment]
环境应该没问题。有可能是装的mxnet有问题，你看看在python3.5里，直接 `import mxnet`会不会报同样的错误。会的话把mxnet卸载了重装试试

**Comment by xiaoyuergo** [comment]
import mxnet 是报这个错，
>>> import mxnet
Illegal instruction (core dumped)

我卸载了，这边有合适的教程吗，还需要装其他的，是装CPU的还是GPU的

**Comment by xiaoyuergo** [comment]
顶上，上述问题？

**Comment by xiaoyuergo** [comment]
更新下吧，终于搞好了，主要是环境问题，最后换成阿里云服务，系统ubuntu 18情况下    三下五除二 几分钟就搞定了。环境对了，90% 就快成功了

**Comment by breezedeus** [comment]
👍
