### ISSUE TITLE
关于初始化ocr = CnOcr()时的输出问题

### ISSUE THREAD

**Issue by Chandler-Lu** [breezedeus/cnocr#68]
您好，在进行初始化`ocr = CnOcr()`时，总会有`loading model parameters from dir /Users/xxx/.cnocr/1.1.0/conv-lite-fc`的输出，在用于制作某些工作流工具脚本时，该输出可能会被程序捕获作为正式结果输出，不知道是否有关闭该输出的方案，谢谢。

https://github.com/breezedeus/cnocr/blob/0f09b27c37fd6993737f61dba38cc9dfede27a1e/cnocr/cn_ocr.py#L170

**Comment by breezedeus** [comment]
@Chandler-Lu 没想到还有这种坏处，我争取明后天发个新版，处理下打印问题。

**Comment by Chandler-Lu** [comment]
感谢感谢，不过这个还是依你们的需求为主，我这个就是小众需求hhhh

**Comment by breezedeus** [comment]
@Chandler-Lu 如果改成用logger输出是否能满足你的需求？可以把logger输出到文件而不打印出来

**Comment by Chandler-Lu** [comment]
logger没有问题～

**Comment by breezedeus** [comment]
@Chandler-Lu 已更新到 V1.1.1

**Comment by Chandler-Lu** [comment]
感谢！已经没问题了
