### ISSUE TITLE
请问这个大并发图片识别文字情况下，这个如何解决

### ISSUE THREAD

**Issue by xiaoyuergo** [breezedeus/cnocr#69]
我试用开启固定5个进程处理这个文字识别，但不一会 就报内存不够  500错误，用完好像并没有及时释放内存，请问该如何优化这块？

**Comment by breezedeus** [comment]
@xiaoyuergo 内存消耗会越来越大？我明天看看能不能复现

**Comment by xiaoyuergo** [comment]
> @xiaoyuergo 内存消耗会越来越大？我明天看看能不能复现
第一种：我就flask 当容器连续请求一会  2G内存就不够了，报memory out。
第二种：我用flask当容器，gunicorn 控制2进程数，5个线程   然后间隔连续请求，几分钟后也报memory out 或者500 错误。

**Comment by breezedeus** [comment]
@xiaoyuergo 我这边尝试没这个问题。你是会每次重新初始化吗？

**Comment by myuanz** [comment]
> > @xiaoyuergo 内存消耗会越来越大？我明天看看能不能复现
> > 第一种：我就flask 当容器连续间隔请求文字识别  刚开始每次都能识别文字并正常返回，几分钟后2G内存就不够了，报memory out。
> > 第二种：我用flask当容器，gunicorn 控制2进程数，5个线程   然后间隔连续请求，几分钟后也报memory out 或者500 错误。

https://github.com/breezedeus/cnocr/pull/85

试试这个?

**Comment by gdzqzzx** [comment]
> > > @xiaoyuergo 内存消耗会越来越大？我明天看看能不能复现
> > > 第一种：我就flask 当容器连续间隔请求文字识别  刚开始每次都能识别文字并正常返回，几分钟后2G内存就不够了，报memory out。
> > > 第二种：我用flask当容器，gunicorn 控制2进程数，5个线程   然后间隔连续请求，几分钟后也报memory out 或者500 错误。
> 
> #85
> 
> 试试这个?

这个方法对我的图片未能奏效（应该是因为图片太大了）。
根据[#9474](https://github.com/apache/incubator-mxnet/issues/13482)，可以尝试

1. 使用mx.gpu(0).empty_cache()
2. 环境变量MXNET_GPU_MEM_POOL_TYPE设大一点（默认为1，可以设到80以上，但是速度会变慢）

但实际上以上两种方法都没能完全释放内存，这好像是mxnet现在还没解决的问题。

**Comment by myuanz** [comment]
> > > > @xiaoyuergo 内存消耗会越来越大？我明天看看能不能复现
> > > > 第一种：我就flask 当容器连续间隔请求文字识别  刚开始每次都能识别文字并正常返回，几分钟后2G内存就不够了，报memory out。
> > > > 第二种：我用flask当容器，gunicorn 控制2进程数，5个线程   然后间隔连续请求，几分钟后也报memory out 或者500 错误。
> > 
> > 
> > #85
> > 试试这个?
> 
> 这个方法对我的图片未能奏效（应该是因为图片太大了）。
> 根据[#9474](https://github.com/apache/incubator-mxnet/issues/13482)，可以尝试
> 
> 1. 使用mx.gpu(0).empty_cache()
> 2. 环境变量MXNET_GPU_MEM_POOL_TYPE设大一点（默认为1，可以设到80以上，但是速度会变慢）
> 
> 但实际上以上两种方法都没能完全释放内存，这好像是mxnet现在还没解决的问题。

你的图片有多大? 我的是800*1000这么大

**Comment by gdzqzzx** [comment]
> > > > > @xiaoyuergo 内存消耗会越来越大？我明天看看能不能复现
> > > > > 第一种：我就flask 当容器连续间隔请求文字识别  刚开始每次都能识别文字并正常返回，几分钟后2G内存就不够了，报memory out。
> > > > > 第二种：我用flask当容器，gunicorn 控制2进程数，5个线程   然后间隔连续请求，几分钟后也报memory out 或者500 错误。
> > > 
> > > 
> > > #85
> > > 试试这个?
> > 
> > 
> > 这个方法对我的图片未能奏效（应该是因为图片太大了）。
> > 根据[#9474](https://github.com/apache/incubator-mxnet/issues/13482)，可以尝试
> > 
> > 1. 使用mx.gpu(0).empty_cache()
> > 2. 环境变量MXNET_GPU_MEM_POOL_TYPE设大一点（默认为1，可以设到80以上，但是速度会变慢）
> > 
> > 但实际上以上两种方法都没能完全释放内存，这好像是mxnet现在还没解决的问题。
> 
> 你的图片有多大? 我的是800*1000这么大

是文字转图片的长微博，所以非常长。宽度是500到800之间，长度大概是6000到20000之间。所以我只能使用命令行单张图片处理。

**Comment by breezedeus** [comment]
line_split后行图片太多？试试自己做line_split，然后按固定大小batch送给 ocr_for_single_line

**Comment by djaym7** [comment]
I have the same exact problem where the stale memory keeps increasing untill CUDA out of memory error. This needs to be solved asap!

**Comment by djaym7** [comment]
Doing simple allocation and clearing cache and deleting variable doesnt clear all memory!
    ctx = mx.gpu(0)
    arr = mx.nd.ones((200,200), ctx=ctx)
    del arr
    ctx.empty_cache()

**Comment by djaym7** [comment]
https://github.com/breezedeus/cnocr/issues/137
