### ISSUE TITLE
黑白与灰阶图支持

### ISSUE THREAD

**Issue by yilu1015** [breezedeus/cnocr#71]
为节省空间，本人扫描文档时，常以黑白或灰阶图保存。请问今后会考虑支持这两种颜色模式吗？谢谢！

**Comment by breezedeus** [comment]
没明白，能给几个示例吗？

**Comment by yilu1015** [comment]
附件中两张图，一张是黑白模式，一张是RGB，使用如下代码，前者无法OCR。

`
from cnocr import CnOcr
ocr = CnOcr(model_name='conv-lite-fc', model_epoch=None)
res = ocr.ocr('X') # rgb.jpg or bw.jpg
print("Predicted Chars:", res)
`
![bw](https://user-images.githubusercontent.com/25930948/80297116-6af71d00-874e-11ea-836f-31d64f1600e5.jpg)
![rgb](https://user-images.githubusercontent.com/25930948/80297118-6b8fb380-874e-11ea-9a3d-daf1bbbe7080.jpg)

**Comment by breezedeus** [comment]
@yilu1015 现在识别的流程是先对图片的文字分行，然后逐行识别。第一张图识别不出来的原因是分行不对。分行不对应该是因为坐标那条竖线。第一张图中的竖线比第二张中的粗。

**Comment by yilu1015** [comment]
谢谢！我原以为是图片颜色是黑白造成。

许多扫描件都有类似的竖线，如果能够有办法改进分行，增强识别，将大有裨益。
