### ISSUE TITLE
初始化时model_name设置成其他模型会报错

### ISSUE THREAD

**Issue by Brook-Lan** [breezedeus/cnocr#72]
ocr = CnOcr("conv-lite-lstm")                                                           
loading model parameters from dir /Users/lhq/.cnocr/1.1.0/conv-lite-lstm
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-22-ee2f255daf82> in <module>
----> 1 ocr = CnOcr("conv-lite-lstm")

~/py_env/data_mining/lib/python3.7/site-packages/cnocr/cn_ocr.py in __init__(self, model_name, model_epoch, cand_alphabet, root)
    141         self._hp._loss_type = None  # infer mode
    142 
--> 143         self._mod = self._get_module()
    144 
    145     def _assert_and_prepare_model_files(self):

~/py_env/data_mining/lib/python3.7/site-packages/cnocr/cn_ocr.py in _get_module(self)
    170         print('loading model parameters from dir %s' % self._model_dir)
    171         mod = load_module(
--> 172             prefix, self._model_epoch, data_names, data_shapes, network=network
    173         )
    174         return mod

~/py_env/data_mining/lib/python3.7/site-packages/cnocr/cn_ocr.py in load_module(prefix, epoch, data_names, data_shapes, network)
     98     )
     99     mod.bind(for_training=False, data_shapes=data_shapes)
--> 100     mod.set_params(arg_params, aux_params, allow_missing=False)
    101     return mod
    102 

~/py_env/data_mining/lib/python3.7/site-packages/mxnet/module/module.py in set_params(self, arg_params, aux_params, allow_missing, force_init, allow_extra)
    348             self.init_params(initializer=None, arg_params=arg_params, aux_params=aux_params,
    349                              allow_missing=allow_missing, force_init=force_init,
--> 350                              allow_extra=allow_extra)
    351             return
    352 

~/py_env/data_mining/lib/python3.7/site-packages/mxnet/module/module.py in init_params(self, initializer, arg_params, aux_params, allow_missing, force_init, allow_extra)
    307         for name, arr in sorted(self._arg_params.items()):
    308             desc = InitDesc(name, attrs.get(name, None))
--> 309             _impl(desc, arr, arg_params)
    310 
    311         for name, arr in sorted(self._aux_params.items()):

~/py_env/data_mining/lib/python3.7/site-packages/mxnet/module/module.py in _impl(name, arr, cache)
    298                 else:
    299                     if not allow_missing:
--> 300                         raise RuntimeError("%s is not presented" % name)
    301                     if initializer is not None:
    302                         initializer(name, arr)

RuntimeError: lstm4_l0_h2h_bias is not presented

**Comment by breezedeus** [comment]
@Brook-Lan 看看你mxnet的版本是多少？我这没问题啊
