### ISSUE TITLE
Download urls of models are wrong

### ISSUE THREAD

**Issue by DCMMC** [breezedeus/cnocr#73]
Hi.
After upgrading cnocr to version `1.1.1`, the download links of models are incorrect.
Because the repo `breezedeus/cnocr-models` does not exist models with version `1.1.1` at present.

```
RuntimeError: Failed downloading url 
https://raw.githubusercontent.com/breezedeus/cnocr-models/master/models/1.1.1/conv-lite-lstm.zip
```

**Comment by breezedeus** [comment]
@DCMMC Thanks for trying. This bug is just fixed at V1.1.2.
