### ISSUE TITLE
能否返回文字的坐标？

### ISSUE THREAD

**Issue by wmjie** [breezedeus/cnocr#76]
您好，这个识别比pytesseract识别率高不少啊。
向咨询一下有计划增加文字在图片中坐标位置的功能吗？

**Comment by breezedeus** [comment]
@wmjie 近期看看能不能加个粗略的位置

**Comment by monkey1990** [comment]
顶一下，建议增加文字坐标，比较需要这个能力

**Comment by lvbohui** [comment]
+1
同样需要这个功能
最好是有每个文字，字符的坐标，可以给出离图片上边缘距离，左边缘距离这种类似的是最好了

**Comment by zhongfuxiao** [comment]
所以现在加了吗？

**Comment by breezedeus** [comment]
新版已加
