### ISSUE TITLE
GPU、

### ISSUE THREAD

**Issue by breezewhp** [breezedeus/cnocr#77]

**Comment by breezewhp** [comment]
pip安装完后。
调用发现，OCR过程未占用GPU。

**Comment by breezedeus** [comment]
@breezewhp 嗯，现在预测部分只支持cpu，训练才支持gpu

**Comment by jaycecd** [comment]
context=mx.gpu()不行吗？

**Comment by breezedeus** [comment]
改下代码应该就可以，会在下个版本支持

**Comment by breezewhp** [comment]
感谢@breezedeus您的耐心回答。
通过您和热心网友的指导，自己总结下解决方案。
1、安装mxnet_cuda。
2、修改cn_ocr.py源码（99行左右）：
`    # whp
    try: #GPU
        mod = mx.mod.Module(symbol=sym, context=mx.gpu(), data_names=data_names, label_names=None)
    except: #CPU
        mod = mx.mod.Module(symbol=sym, context=mx.cpu(), data_names=data_names, label_names=None)
    #
`

**Comment by myuanz** [comment]
> 感谢@breezedeus您的耐心回答。
> 通过您和热心网友的指导，自己总结下解决方案。
> 1、安装mxnet_cuda。
> 2、修改cn_ocr.py源码（99行左右）：
> `mod = mx.mod.Module(symbol=sym, context=mx.gpu(), data_names=data_names, label_names=None)`

感谢您的尝试, 我再补充一点: 

Windows 下在 Jupyter 中使用该方案会造成 GPU 内存泄露, 直接运行脚本即可避免
