### ISSUE TITLE
mxnet版本问题

### ISSUE THREAD

**Issue by jaycecd** [breezedeus/cnocr#78]
![image](https://user-images.githubusercontent.com/33342388/80857626-1d1a7180-8c86-11ea-8d48-a7101bc408a3.png)

如上图：mxnet依赖升级到更新的版本了。很多人反馈mxnet 1.4.1经常找不到没法装，现在升级到>=1.5.0,<1.7.0。
但是我看到requirements.txt里面的mxnet还是1.4.1呀？是描述错了吗？

**Comment by breezedeus** [comment]
@jaycecd 嗯，是requirement里忘改了，setup里已经改过了
