### ISSUE TITLE
数据集构造

### ISSUE THREAD

**Issue by jianjunwu** [breezedeus/cnocr#81]
感谢作者的无私贡献，想问一下您在构造训练集的时候的处理过程大概是什么样的？是否固定文字数量，比如汉字10个，英文20个这样。对于长宽不同的图片的处理是怎样的呢？

**Comment by breezedeus** [comment]
@jianjunwu 训练集是宽度一样的，都是280。汉字的话就是10个字，英文的话就是随机单词组合，总共截断到包含20个字母。用的是我自己fork 的 text_render：https://github.com/breezedeus/text_renderer ，可以参考 https://github.com/breezedeus/text_renderer/blob/master/Makefile 这个文件

**Comment by jianjunwu** [comment]
@breezedeus 再问一下您，您的训练集中都是10个中文字或者20个英文字嘛？因为我之前训练的时候尝试过不定长的中文字（<=10），然后通过padding成宽度280，但感觉模型很难收敛。

**Comment by yerui2018** [comment]
text_render这个工具挺好的  缺少一种场景，文字的像素点存在较多缺失的情况，需要自己搞一下

**Comment by breezedeus** [comment]
@jianjunwu 我的训练集中都是10个中文字或者20个英文字的。

**Comment by jianjunwu** [comment]
@breezedeus 谢谢您，您一般训练几轮后模型收敛呀？我基于caffe的360万生成的数据集+您推荐text_renderer 生成的150万数据集，感觉收敛很慢，3个epoch后loss停止在0.3，就很难再下降，训练集的准确率大概0.957.

**Comment by breezedeus** [comment]
@jianjunwu 我一般训练 20~40 epochs

**Comment by breezedeus** [comment]
loss不下降可以把badcases拿出来看看，有些生成的数据不理想，需要去掉

**Comment by dennisgu** [comment]
> text_render这个工具挺好的 缺少一种场景，文字的像素点存在较多缺失的情况，需要自己搞一下
你好，这种情况在实际的票据针打字符、少墨时经常发生，能否分享一下仿真文字像素缺失的实现代码？

**Comment by yerui2018** [comment]
> > text_render这个工具挺好的 缺少一种场景，文字的像素点存在较多缺失的情况，需要自己搞一下
> 
> @yerui2018 你好，这种情况在实际的票据针打字符、少墨时经常发生，能否分享一下仿真文字像素缺失的实现代码？

@dennisgu 代码是我同事写的，我不会写这些代码。晚点我让同事发你吧。给个邮箱地址呗。或者给你个思路也可以。我记得当时我们也是根据csdn中一个博主提供的思路，自己实现的。

**Comment by dennisgu** [comment]
> > > text_render这个工具挺好的 缺少一种场景，文字的像素点存在较多缺失的情况，需要自己搞一下
> > 
> > 
> > @yerui2018 你好，这种情况在实际的票据针打字符、少墨时经常发生，能否分享一下仿真文字像素缺失的实现代码？
> 
> @dennisgu 代码是我同事写的，我不会写这些代码。晚点我让同事发你吧。给个邮箱地址呗。或者给你个思路也可以。我记得当时我们也是根据csdn中一个博主提供的思路，自己实现的。

dennisgu@hotmail.com
非常感谢

**Comment by yerui2018** [comment]
> > > > text_render这个工具挺好的 缺少一种场景，文字的像素点存在较多缺失的情况，需要自己搞一下
> > > 
> > > 
> > > @yerui2018 你好，这种情况在实际的票据针打字符、少墨时经常发生，能否分享一下仿真文字像素缺失的实现代码？
> > 
> > 
> > @dennisgu 代码是我同事写的，我不会写这些代码。晚点我让同事发你吧。给个邮箱地址呗。或者给你个思路也可以。我记得当时我们也是根据csdn中一个博主提供的思路，自己实现的。
> 
> @yerui2018 [dennisgu@hotmail.com](mailto:dennisgu@hotmail.com)
> 非常感谢

邮件已发送。代码比较粗糙。你根据需求自行修改吧。

**Comment by dennisgu** [comment]
好的，感谢分享！

发自我的iPhone

在 2020年8月11日，上午9:04，yerui2018 <notifications@github.com> 写道：

﻿

text_render这个工具挺好的 缺少一种场景，文字的像素点存在较多缺失的情况，需要自己搞一下

@yerui2018<https://eur06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fyerui2018&data=02%7C01%7C%7C879ec1c405974cf6b2e608d83d92859c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637327046795338626&sdata=OnQM0ewp8gAghRJQXmgp6gSinW%2B0PuWxDgX8w%2BJAbPU%3D&reserved=0> 你好，这种情况在实际的票据针打字符、少墨时经常发生，能否分享一下仿真文字像素缺失的实现代码？

@dennisgu<https://eur06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdennisgu&data=02%7C01%7C%7C879ec1c405974cf6b2e608d83d92859c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637327046795338626&sdata=YrggqxVuY0lln72bIzslhSyXwSJjnvlLzydTXKV%2B10c%3D&reserved=0> 代码是我同事写的，我不会写这些代码。晚点我让同事发你吧。给个邮箱地址呗。或者给你个思路也可以。我记得当时我们也是根据csdn中一个博主提供的思路，自己实现的。

@yerui2018<https://eur06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fyerui2018&data=02%7C01%7C%7C879ec1c405974cf6b2e608d83d92859c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637327046795348621&sdata=TT8BvHB%2FwHRs9InnQ99hAK%2Fwd4wWJI8JhEUrce9O0N8%3D&reserved=0> dennisgu@hotmail.com<mailto:dennisgu@hotmail.com>
非常感谢

邮件已发送。代码比较粗糙。你根据需求自行修改吧。
