### ISSUE TITLE
空白较多时无法识别

### ISSUE THREAD

**Issue by yangyaofei** [breezedeus/cnocr#82]
在空白较多的时候,ocr结果很差.对于单行但是空白很多的时候,图片貌似没有被很好的分割,比如下面这个

![image](https://user-images.githubusercontent.com/7934098/81781756-3bf0f180-952b-11ea-98d6-38c11af978e6.png)

**Comment by breezedeus** [comment]
@yangyaofei 我试了下，原因是黑边，去掉黑边后识别就没问题了

**Comment by yangyaofei** [comment]
谢谢
