### ISSUE TITLE
自己训练的模型，不支持空格识别？

### ISSUE THREAD

**Issue by breezewhp** [breezedeus/cnocr#83]
您好，
我按照data/sample-data的样例，构建带“空格”的数据集，转化成recordio数据。
训练后，发现得到的模型模型不支持“空格”了。
请问这是什么原因导致的呢？

**Comment by breezedeus** [comment]
@breezewhp 可能是你的数据集不够大

**Comment by louguozhe** [comment]
请问训练自己的模型，需要多大的训练集，比如说手写字体识别

**Comment by louguozhe** [comment]
@breezedeus 请问训练如果要训练自己的模型，一般需要多大的训练集，比如说手写字体识别

**Comment by Jack-Lee1994** [comment]
@breezedeus 您好，我也有类似的问题，如果要使训练出来的模型支持空格，需要多大的数据集来训练，空格的数量大概是多少呢

**Comment by breezedeus** [comment]
几十万张图片应该就行
