### ISSUE TITLE
请问：RuntimeError: Cannot find the MXNet library.

### ISSUE THREAD

**Issue by NedLi** [breezedeus/cnocr#86]
您好!

我是初次安装并使用该安装包。

在执行您所给出的示例代码时，我这里显示如下的错误信息。

请问我是需要重新安装MXNet 吗？（已Successfully installed mxnet-1.6.0）谢谢！

Traceback (most recent call last):
  File "C:\My Documents\Scripts\ocrtest.py", line 1, in <module>
    from cnocr import CnOcr
  File "C:\Python38\lib\site-packages\cnocr\__init__.py", line 1, in <module>
    from .cn_ocr import CnOcr
  File "C:\Python38\lib\site-packages\cnocr\cn_ocr.py", line 20, in <module>
    import mxnet as mx
  File "C:\Python38\lib\site-packages\mxnet\__init__.py", line 24, in <module>
    from .context import Context, current_context, cpu, gpu, cpu_pinned
  File "C:\Python38\lib\site-packages\mxnet\context.py", line 24, in <module>
    from .base import classproperty, with_metaclass, _MXClassPropertyMetaClass
  File "C:\Python38\lib\site-packages\mxnet\base.py", line 214, in <module>
    _LIB = _load_lib()
  File "C:\Python38\lib\site-packages\mxnet\base.py", line 204, in _load_lib
    lib_path = libinfo.find_lib_path()
  File "C:\Python38\lib\site-packages\mxnet\libinfo.py", line 73, in find_lib_path
    raise RuntimeError('Cannot find the MXNet library.\n' +
RuntimeError: Cannot find the MXNet library.
List of candidates:
C:\Python38\lib\site-packages\mxnet\libmxnet.dll
C:\Python38\lib\site-packages\mxnet\../../lib/libmxnet.dll
C:\Python38\lib\site-packages\mxnet\../../build/libmxnet.dll
C:\Python38\lib\site-packages\mxnet\../../build\libmxnet.dll
C:\Python38\lib\site-packages\mxnet\../../build\Release\libmxnet.dll
C:\Python38\lib\site-packages\mxnet\../../windows\Release\libmxnet.dll

**Comment by breezedeus** [comment]
看着是你的mxnet没装好啊，试试uninstall后重新装下，然后命令行用 `python -m pip freeze` 看看里面是否有mxnet

**Comment by NedLi** [comment]
谢谢回复！

我利用“python -m pip freeze”查了一下，显示“mxnet==1.6.0”。把这个包卸载了以后，重新安装了一下，还是显示同样的错误。

根据https://mxnet.apache.org/get_started/windows_setup.html上所说的，Install with Intel CPUs 需要额外的步骤。可能这就是造成错误的根本原因。

**Comment by myuanz** [comment]
> 谢谢回复！
> 
> 我利用“python -m pip freeze”查了一下，显示“mxnet==1.6.0”。把这个包卸载了以后，重新安装了一下，还是显示同样的错误。
> 
> 根据[https://mxnet.apache.org/get_started/windows_setup.html上所说的，Install](https://mxnet.apache.org/get_started/windows_setup.html%E4%B8%8A%E6%89%80%E8%AF%B4%E7%9A%84%EF%BC%8CInstall) with Intel CPUs 需要额外的步骤。可能这就是造成错误的根本原因。

我记得我在 3.8 失败过, 你要不试试 Python3.7, 并且用 Anaconda 的基础环境

**Comment by NedLi** [comment]
> 我记得我在 3.8 失败过, 你要不试试 Python3.7, 并且用 Anaconda 的基础环境

谢谢您的建议！

试了下Colab，可以执行所给出的示例代码并返回识别结果。安装这两个包即可：

!pip install mxnet==1.6.0b20200101
!pip install cnocr

**Comment by ywzhaiqi** [comment]
> > 我记得我在 3.8 失败过, 你要不试试 Python3.7, 并且用 Anaconda 的基础环境
> 
> 谢谢您的建议！
> 
> 试了下Colab，可以执行所给出的示例代码并返回识别结果。安装这两个包即可：
> 
> !pip install mxnet==1.6.0b20200101
> !pip install cnocr

同样的问题。`pip install mxnet==1.6.0b20200101`

> No matching distribution found for mxnet==1.6.0b20200101

**Comment by yerui2018** [comment]
我是用Python3.6.8版本的   没有使用Anaconda，没遇到什么问题。
