### ISSUE TITLE
ImportError: cannot import name 'contrib'  ?

### ISSUE THREAD

**Issue by xiaoyuergo** [breezedeus/cnocr#88]
ImportError: cannot import name 'contrib'
请问这是什么原因？该如何解决

**Comment by breezedeus** [comment]
可能是mxnet的版本或者安装有问题。试试卸载了重装  v1.6.0

**Comment by xiaoyuergo** [comment]
> 可能是mxnet的版本或者安装有问题。试试卸载了重装 v1.6.0

嗯，卸掉mxnet然后执行下面之后  就好了
pip install mxnet==1.6.0b20200101
