### ISSUE TITLE
多行文本识别问题

### ISSUE THREAD

**Issue by Jinnrry** [breezedeus/cnocr#9]
我看了您的实现，当遇到文件行距特别小，小到上下行偶尔有粘连的时候就无法分割开了。我尝试了用滴水算法去进行分割，效果也不理想，这种情况还有什么好的算法处理吗。还有一个思路是尝试再训练一个模型来专门做分割，但是找了半天也没找到有可以用的训练集

**Comment by breezedeus** [comment]
嗯，常用的就是ctpn了
