### ISSUE TITLE
关于本机（Windows）和服务器运行结果不一致的问题

### ISSUE THREAD

**Issue by RFHzhj** [breezedeus/cnocr#90]
同样的代码，同样的图片，为什么在本地和在服务器识别结果不一样呢？
在本机识别时会出现一些乱七八糟的内容，而在服务器识别结果基本都是正确的

**Comment by breezedeus** [comment]
用的都是cpu吗？模型一样的对吧

**Comment by RFHzhj** [comment]
@breezedeus 是的，都是CPU，模型用的一样

**Comment by yerui2018** [comment]
需要把server和桌面端使用的piplist发出来确认一下，比较容易定位问题吧。

**Comment by RFHzhj** [comment]
@yerui2018 谢谢 我刚看了下应该是cnocr的版本问题 十分感谢

**Comment by yerui2018** [comment]
不用客气，这个issue可以close了。
