### ISSUE TITLE
cannot import name 'CnOcr' from 'cnocr'

### ISSUE THREAD

**Issue by kennethhome** [breezedeus/cnocr#98]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'CnOcr' from 'cnocr'

**Comment by momo1054** [comment]
请问这个怎么解决的

**Comment by Chandler-Lu** [comment]
> 请问这个怎么解决的

py的文件名不要叫cnocr.py。。
